// AUTO-GENERATED BY sync.ps1
// Source: yr9\Maths\index.html

export const title = "THSC Online - Year 9 Maths Resources";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="current reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="element"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr9/">Year 9 →</a>&nbsp;
<a className="current" href="/s/yr9/Maths/">Maths →</a>&nbsp;
<a className="reverse" href="../">↖ [<i>Up One Folder</i>]</a>
</div></div>
<div id="content-all">
<h3><span className="title"><img src="/s/images/colours/icon_red.png" />&nbsp;&nbsp;Year 9 Maths Resources</span></h3>
<div id="web-list">
<div><div><div>
<details className="smallscreen" style={{ display: 'none' }}><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png" />&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../">Back to Year 9</a></span><br /><br />
</details>
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="yr9papers.html">Maths Year 9 Yearly Papers </a><br />
<span style={{ paddingLeft: '29px' }}>77 papers online, 56 w. sol</span></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="assessment-tasks.html">Maths Year 9 Internal Assessment Tasks</a><br />
<span style={{ paddingLeft: '29px' }}>19 papers online, 16 w. sol</span></span><br />  

</div></div></div></div>
</div>
        </>
    );
}
