// AUTO-GENERATED BY sync.ps1
// Source: yr11\Chemistry\prelimpapers.html

export const title = "THSC Online - Year 11 Chemistry Yearly Exam Papers";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="current"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="element"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr11/">Year 11 - Preliminary →</a>&nbsp;
<a href="/s/yr11/Chemistry/">Chemistry →</a>&nbsp;
<a className="current" href="/s/yr11/Chemistry/prelimpapers.html">Past Yearly Exams →</a>&nbsp;
<a className="reverse" href="index.html">↖ [<i>Up One Folder</i>]</a>
</div></div>
<div id="content-all">
<h4>Year 11 Chemistry Yearly Exams</h4>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png">&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="../">Back to Year 11 - Preliminary</a></span><br />
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="index.html">Up One Folder</a></span><br /><br />
</details>
<table className="listing" id="papers-by-school"><tbody>
<tr className="content"><td><span style="color:#0000FF;"><b>Note: </b></span>Some materials listed are from old syllabus prescriptions.</td></tr>
<tr className="content"><td><span style="color:#0000FF;"><b>Note 2: </b></span>2021 exams were conducted online, so the format of materials listed may differ slightly.</td></tr>
<tr className="content"><td>
<ul>
<li>Sample answers or marking guidelines included with most papers.</li>
<li>To contribute past papers or other practice questions, <a href="/s/upload">upload files here</a></li>
</ul></td></tr>

<tr><td><details open><summary>Barker</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Barker 2019</a>
</span></details></td></tr>
<tr><td><details open><summary>Baulkham Hills</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Baulkham Hills 2008 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Baulkham Hills 2009 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Baulkham Hills 2012 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Caringbah</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Caringbah 2022</a>
</span></details></td></tr>
<tr><td><details open><summary>Fort St</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Fort St 2019 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Fort St 2022 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Girraween</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Girraween 2019</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Girraween 2020 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Girraween 2022 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Hornsby Girls</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Hornsby Girls 2018 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Hurlstone</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Hurlstone 2018</a>
</span></details></td></tr>
<tr><td><details open><summary>International Grammar</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>International Grammar 2019</a>
</span></details></td></tr>
<tr><td><details open><summary>James Ruse</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2001 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2002 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2003 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2004 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2005 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2006 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2007 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2008 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2010 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2011 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2012 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2013 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2014 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2015 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2016 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2018 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2019 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2020 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>James Ruse 2021 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Killara</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Killara 2024 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Knox</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Knox 2009</a>
</span></details></td></tr>
<tr><td><details open><summary>North Sydney Girls</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>North Sydney Girls 2019 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>North Sydney Girls 2020 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>North Sydney Girls 2022 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>North Sydney Girls 2023 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>North Sydney Girls 2024 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Penrith</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Penrith 2010</a>
</span></details></td></tr>
<tr><td><details open><summary>Presbyterian</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Presbyterian 2018 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Pymble</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Pymble 2002</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Pymble 2003</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Pymble 2006</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Pymble 2018 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Pymble 2020</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Pymble 2023 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Riverview</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Riverview 2018</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Riverview 2022 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Riverview 2023 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Riverview 2024 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Shore</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Shore 2023 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Smiths Hill</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Smiths Hill 2022</a>
</span></details></td></tr>
<tr><td><details open><summary>St Aloysius</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>St Aloysius 2022 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Strathfield Girls</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Strathfield Girls 2004</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Strathfield Girls 2006</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Strathfield Girls 2011 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Strathfield Girls 2012</a>
</span></details></td></tr>
<tr><td><details open><summary>Sydney Boys</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Boys 2004</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Boys 2018 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Boys 2019</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Boys 2020</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Boys 2022</a>
</span></details></td></tr>
<tr><td><details open><summary>Sydney Girls</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Girls 2001</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Girls 2019 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Girls 2020 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Girls 2023 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Girls 2024 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Sydney Grammar</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Grammar 2014 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Grammar 2016 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Grammar 2017 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Grammar 2018 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Grammar 2020 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Grammar 2021 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Grammar 2022 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1818)}>Sydney Grammar 2023 w. sol</a>
</span></details></td></tr>

</tbody></table>
</div>
        </>
    );
}
