// AUTO-GENERATED BY sync.ps1
// Source: yr12\PDHPE\trialpapers.html

export const title = "THSC Online - HSC PDHPE Trial Papers";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;
<a href="/s/yr12/PDHPE/">PDHPE →</a>&nbsp;
<a className="current" href="/s/yr12/PDHPE/trialpapers.html">Past Trials →</a>&nbsp;
<a className="reverse" href="index.html">↖ [<i>Up One Folder</i>]</a>
</div></div>  
<div id="content-all">
<h4>HSC PDHPE Trial Papers</h4>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png" />&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../">Back to Year 12 - HSC</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="index.html">Up One Folder</a></span><br /><br />
</details>
<table className="listing" id="papers-by-school"><tbody>
<tr className="content"><td><span style="color:#0000FF;"><b>Note: </b></span>Some materials listed are from old syllabus prescriptions.</td></tr>
<tr className="content"><td><span style="color:#0000FF;"><b>Note 2: </b></span>2021 exams were conducted online, so the format of materials listed may differ slightly.</td></tr>
<tr className="content"><td>
<ul>
<li>Sample answers or marking guidelines included with most papers.</li>
<li>To contribute past papers or other practice questions, <a href="/s/upload">upload files here</a></li>
</ul></td></tr>

<tr><td><details open><summary>Ascham</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Ascham 2019 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Ascham 2020 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Ascham 2021 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Killara</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Killara 2023</a>
</span></details></td></tr>
<tr><td><details open><summary>Newcastle Grammar</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Newcastle Grammar 2016</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Newcastle Grammar 2017</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Newcastle Grammar 2022</a>
</span></details></td></tr>
<tr><td><details open><summary>Penrith</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Penrith 2021</a>
</span></details></td></tr>
<tr><td><details open><summary>Pymble</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Pymble 2023</a>
</span></details></td></tr>
<tr><td><details open><summary>Scots Albury</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Scots Albury 2012</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Scots Albury 2013</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Scots Albury 2015</a>
</span></details></td></tr>
<tr><td><details open><summary>Shore</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Shore 2014 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Shore 2015 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Shore 2016 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Shore 2017 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Shore 2018 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Shore 2019 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 6428)}>Shore 2020 w. sol</a>
</span></details></td></tr>

</tbody></table>
</div>
        </>
    );
}
