// AUTO-GENERATED BY sync.ps1
// Source: yr11\IPT\prelimpapers.html

export const title = "THSC Online - Year 11 IPT Yearly Exam Papers";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="current"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="element"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr11/">Year 11 - Preliminary →</a>&nbsp;
<a href="/s/yr11/IPT/">IPT →</a>&nbsp;
<a className="current" href="/s/yr11/IPT/prelimpapers.html">Past Yearly Exams →</a>&nbsp;
<a className="reverse" href="index.html">↖ [<i>Up One Folder</i>]</a>
</div></div>
<div id="content-all">
<h4>Year 11 IPT Yearly Exams</h4>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png">&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br>
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="../">Back to Year 11 - Preliminary</a></span><br>
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="index.html">Up One Folder</a></span><br><br>
</details>
<table className="listing" id="papers-by-school"><tbody>
<tr className="content"><td><span style="color:#0000FF;"><b>Note: </b></span>Some materials listed are from old syllabus prescriptions.</td></tr>
<tr className="content"><td><span style="color:#0000FF;"><b>Note 2: </b></span>2021 exams were conducted online, so the format of materials listed may differ slightly.</td></tr>
<tr className="content"><td>
<ul>
<li>Sample answers or marking guidelines included with most papers.</li>
<li>To contribute past papers or other practice questions, <a href="/s/upload">upload files here</a></li>
</ul></td></tr>
<tr><td>Cherrybrook Tech<br>
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4118)}>Cherrybrook Tech 2009</a><br>
</span></td></tr>
<tr><td>Hornsby Girls<br>
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4118)}>Hornsby Girls 2015 w. sol</a><br>
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4118)}>Hornsby Girls 2016 w. sol</a><br>
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4118)}>Hornsby Girls 2020 w. sol</a>
</span></td></tr>
<tr><td>James Ruse<br>
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4118)}>James Ruse 2008 w. sol</a><br>
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4118)}>James Ruse 2010 w. sol</a>
</span></td></tr>
</tbody></table>
</div>
        </>
    );
}
