// AUTO-GENERATED BY sync.ps1
// Source: yr12\Maths\Competitions\cp_imo.html

export const title = "THSC Online - International Mathematical Olympiad";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;    
<a href="/s/yr12/Maths/">Maths (Extracurricular) →</a>&nbsp;    
<a href="/s/yr12/Maths/Competitions/">Competitions →</a>&nbsp;
<a className="current" href="/s/yr12/Maths/Competitions/cp_imo.html">IMO →</a>&nbsp;
<a className="reverse" href="index.html">↖ [<i>Up One Folder</i>]</a>
</div></div>
<div id="content-all">
<h4>International Mathematical Olympiad</h4>
<details className="smallscreen" style={{ display: 'none' }}><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png" />&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../">Back to Year 12 - HSC</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="index.html">Up One Folder</a></span><br /><br />
</details>
<table className="listing" id="papers-by-school"><tbody>
<tr><td>Problems<br />
<span className="content">  
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 1959-2003</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2004</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2005</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2006 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2007</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2008</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2009</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2010</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2011</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2012</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2013</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2014</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2015</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2016</a><br />
</span></td></tr>
<tr className="content"><td>
All IMO problems are taken from the shortlisted problems. For solutions from 2006 onwards refer to the shortlist problems.<br /><br />
</td></tr>
<tr><td>Shortlist Problems<br />
<span className="content">  
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2006 Shortlist w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2007 Shortlist w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2008 Shortlist w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2009 Shortlist w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2010 Shortlist w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2011 Shortlist w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2012 Shortlist w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2013 Shortlist w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2014 Shortlist w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2015 Shortlist w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>IMO 2016 Shortlist w. sol</a><br />
</span></td></tr>
</tbody></table>
</div>
        </>
    );
}
