// AUTO-GENERATED BY sync.ps1
// Source: yr12\Maths\Competitions\cp_nordic.html

export const title = "THSC Online - Nordic Mathematical Contest";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;    
<a href="/s/yr12/Maths/">Maths (Extracurricular) →</a>&nbsp;    
<a href="/s/yr12/Maths/Competitions/">Competitions →</a>&nbsp;
<a className="current" href="/s/yr12/Maths/Competitions/cp_nordic.html">Nordic →</a>&nbsp;
<a className="reverse" href="index.html">↖ [<i>Up One Folder</i>]</a>
</div></div>
<div id="content-all">
<h4>Nordic Mathematical Contest</h4>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png" />&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../">Back to Year 12 - HSC</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="index.html">Up One Folder</a></span><br /><br />
</details>
<table className="listing" id="papers-by-school"><tbody>
<tr><td> <br />
<span className="content">  
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 1987-2011 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2012</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2012 Solutions</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2013</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2013 Solutions</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2014</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2014 Solutions</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2015</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2015 Solutions</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2016</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2016 Solutions</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2017</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2017 Solutions</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2018</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 5405)}>Nordic 2018 Solutions</a><br />
</span></td></tr>
</tbody></table>
</div>
        </>
    );
}
