// AUTO-GENERATED BY sync.ps1
// Source: yr12\Maths\Competitions\index.html

export const title = "THSC Online - Maths Competitions";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;    
<a href="/s/yr12/Maths/">Maths (Extracurricular) →</a>&nbsp;    
<a className="current" href="/s/yr12/Maths/Competitions/">Competitions →</a>&nbsp;    
<a className="reverse" href="../">↖ [<i>Up One Folder</i>]</a>    
</div></div>
<div id="content-all">
<h3><span className="title"><img src="/s/images/colours/icon_red.png" />&nbsp;&nbsp;Competitions</span></h3>
<div id="web-list" style="width:700px;">
<div><div><div>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png" />&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../../">Back to Year 12 - HSC</a></span><br /><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../">Back to HSC Maths</a></span><br /><br />
</details>
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="cp_imo.html">International Mathematical Olympiad Papers</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="cp_apmo.html">Asian-Pacific Mathematics Olympiad Papers</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="cp_balkan.html">Balkan Olympiad Papers</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="cp_cmo.html">Canadian Mathematical Olympiad Papers</a></span><br />
<br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="cp_nordic.html">Nordic Mathematical Contest</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="cp_putnam.html">Putnam Competition</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="cp_unsw.html">UNSW Maths Competition</a></span><br />
<br />
More competitions coming soon.<br /><br />
<u>Please note:</u><br />AMC, AIMO and other related papers are not posted online here.
</div></div></div></div>
</div>
        </>
    );
}
