// AUTO-GENERATED BY sync.ps1
// DO NOT EDIT

import Yr10_index_Page3 from "./yr10/index.jsx";
import Yr10_Maths_assessment_tasks_Page4 from "./yr10/Maths/assessment-tasks.jsx";
import Yr10_Maths_index_Page5 from "./yr10/Maths/index.jsx";
import Yr10_Maths_yr10papers_Page6 from "./yr10/Maths/yr10papers.jsx";
import Yr10_Science_index_Page7 from "./yr10/Science/index.jsx";
import Yr10_Science_yr10papers_Page8 from "./yr10/Science/yr10papers.jsx";
import Yr11_Biology_assessment_tasks_Page9 from "./yr11/Biology/assessment-tasks.jsx";
import Yr11_Biology_index_Page10 from "./yr11/Biology/index.jsx";
import Yr11_Biology_prelimpapers_Page11 from "./yr11/Biology/prelimpapers.jsx";
import Yr11_Business_Studies_index_Page12 from "./yr11/Business Studies/index.jsx";
import Yr11_Business_Studies_prelimpapers_Page13 from "./yr11/Business Studies/prelimpapers.jsx";
import Yr11_Chemistry_assessment_tasks_Page14 from "./yr11/Chemistry/assessment-tasks.jsx";
import Yr11_Chemistry_index_Page15 from "./yr11/Chemistry/index.jsx";
import Yr11_Chemistry_prelimpapers_Page16 from "./yr11/Chemistry/prelimpapers.jsx";
import Yr11_Earth_Environmental_Science_index_Page17 from "./yr11/Earth & Environmental Science/index.jsx";
import Yr11_Earth_Environmental_Science_prelimpapers_Page18 from "./yr11/Earth & Environmental Science/prelimpapers.jsx";
import Yr11_Economics_assessment_tasks_Page19 from "./yr11/Economics/assessment-tasks.jsx";
import Yr11_Economics_index_Page20 from "./yr11/Economics/index.jsx";
import Yr11_Economics_prelimpapers_Page21 from "./yr11/Economics/prelimpapers.jsx";
import Yr11_Engineering_Studies_assessment_tasks_Page22 from "./yr11/Engineering Studies/assessment-tasks.jsx";
import Yr11_Engineering_Studies_index_Page23 from "./yr11/Engineering Studies/index.jsx";
import Yr11_Engineering_Studies_prelimpapers_Page24 from "./yr11/Engineering Studies/prelimpapers.jsx";
import Yr11_index_Page25 from "./yr11/index.jsx";
import Yr11_IPT_index_Page26 from "./yr11/IPT/index.jsx";
import Yr11_IPT_prelimpapers_Page27 from "./yr11/IPT/prelimpapers.jsx";
import Yr11_Legal_Studies_index_Page28 from "./yr11/Legal Studies/index.jsx";
import Yr11_Legal_Studies_prelimpapers_Page29 from "./yr11/Legal Studies/prelimpapers.jsx";
import Yr11_Maths_assessment_tasks_accelerated_Page30 from "./yr11/Maths/assessment-tasks_accelerated.jsx";
import Yr11_Maths_assessment_tasks_advanced_Page31 from "./yr11/Maths/assessment-tasks_advanced.jsx";
import Yr11_Maths_assessment_tasks_extension1_Page32 from "./yr11/Maths/assessment-tasks_extension1.jsx";
import Yr11_Maths_index_Page33 from "./yr11/Maths/index.jsx";
import Yr11_Maths_prelimpapers_accelerated_Page34 from "./yr11/Maths/prelimpapers_accelerated.jsx";
import Yr11_Maths_prelimpapers_advanced_Page35 from "./yr11/Maths/prelimpapers_advanced.jsx";
import Yr11_Maths_prelimpapers_extension1_Page36 from "./yr11/Maths/prelimpapers_extension1.jsx";
import Yr11_Maths_prelimpapers_general_Page37 from "./yr11/Maths/prelimpapers_general.jsx";
import Yr11_Modern_History_index_Page38 from "./yr11/Modern History/index.jsx";
import Yr11_Modern_History_prelimpapers_Page39 from "./yr11/Modern History/prelimpapers.jsx";
import Yr11_Physics_assessment_tasks_Page40 from "./yr11/Physics/assessment-tasks.jsx";
import Yr11_Physics_index_Page41 from "./yr11/Physics/index.jsx";
import Yr11_Physics_prelimpapers_Page42 from "./yr11/Physics/prelimpapers.jsx";
import Yr12_Agriculture_assessment_tasks_Page43 from "./yr12/Agriculture/assessment-tasks.jsx";
import Yr12_Agriculture_index_Page44 from "./yr12/Agriculture/index.jsx";
import Yr12_Agriculture_trialpapers_Page45 from "./yr12/Agriculture/trialpapers.jsx";
import Yr12_Ancient_History_hscpapers_Page46 from "./yr12/Ancient History/hscpapers.jsx";
import Yr12_Ancient_History_index_Page47 from "./yr12/Ancient History/index.jsx";
import Yr12_Ancient_History_trialpapers_Page48 from "./yr12/Ancient History/trialpapers.jsx";
import Yr12_Biology_assessment_tasks_Page49 from "./yr12/Biology/assessment-tasks.jsx";
import Yr12_Biology_hscpapers_Page50 from "./yr12/Biology/hscpapers.jsx";
import Yr12_Biology_index_Page51 from "./yr12/Biology/index.jsx";
import Yr12_Biology_trialpapers_Page52 from "./yr12/Biology/trialpapers.jsx";
import Yr12_Business_Studies_assessment_tasks_Page53 from "./yr12/Business Studies/assessment-tasks.jsx";
import Yr12_Business_Studies_hscpapers_Page54 from "./yr12/Business Studies/hscpapers.jsx";
import Yr12_Business_Studies_index_Page55 from "./yr12/Business Studies/index.jsx";
import Yr12_Business_Studies_trialpapers_Page56 from "./yr12/Business Studies/trialpapers.jsx";
import Yr12_Chemistry_assessment_tasks_Page57 from "./yr12/Chemistry/assessment-tasks.jsx";
import Yr12_Chemistry_hscpapers_Page58 from "./yr12/Chemistry/hscpapers.jsx";
import Yr12_Chemistry_index_Page59 from "./yr12/Chemistry/index.jsx";
import Yr12_Chemistry_trialpapers_Page60 from "./yr12/Chemistry/trialpapers.jsx";
import Yr12_Earth_Environmental_Science_hscpapers_Page61 from "./yr12/Earth & Environmental Science/hscpapers.jsx";
import Yr12_Earth_Environmental_Science_index_Page62 from "./yr12/Earth & Environmental Science/index.jsx";
import Yr12_Earth_Environmental_Science_trialpapers_Page63 from "./yr12/Earth & Environmental Science/trialpapers.jsx";
import Yr12_Economics_assessment_tasks_Page64 from "./yr12/Economics/assessment-tasks.jsx";
import Yr12_Economics_hscpapers_Page65 from "./yr12/Economics/hscpapers.jsx";
import Yr12_Economics_index_Page66 from "./yr12/Economics/index.jsx";
import Yr12_Economics_trialpapers_Page67 from "./yr12/Economics/trialpapers.jsx";
import Yr12_Engineering_Studies_assessment_tasks_Page68 from "./yr12/Engineering Studies/assessment-tasks.jsx";
import Yr12_Engineering_Studies_hscpapers_Page69 from "./yr12/Engineering Studies/hscpapers.jsx";
import Yr12_Engineering_Studies_index_Page70 from "./yr12/Engineering Studies/index.jsx";
import Yr12_Engineering_Studies_trialpapers_Page71 from "./yr12/Engineering Studies/trialpapers.jsx";
import Yr12_English_Ext_1_index_Page72 from "./yr12/English Ext 1/index.jsx";
import Yr12_English_Ext_1_trialpapers_extension1_Page73 from "./yr12/English Ext 1/trialpapers_extension1.jsx";
import Yr12_English_assessment_tasks_Page74 from "./yr12/English/assessment-tasks.jsx";
import Yr12_English_hscpapers_Page75 from "./yr12/English/hscpapers.jsx";
import Yr12_English_index_Page76 from "./yr12/English/index.jsx";
import Yr12_English_trialpapers_paper1_Page77 from "./yr12/English/trialpapers_paper1.jsx";
import Yr12_English_trialpapers_paper2_advanced_Page78 from "./yr12/English/trialpapers_paper2_advanced.jsx";
import Yr12_English_trialpapers_paper2_standard_Page79 from "./yr12/English/trialpapers_paper2_standard.jsx";
import Yr12_History_Extension_index_Page80 from "./yr12/History Extension/index.jsx";
import Yr12_History_Extension_trialpapers_Page81 from "./yr12/History Extension/trialpapers.jsx";
import Yr12_index_Page82 from "./yr12/index.jsx";
import Yr12_Investigating_Science_index_Page83 from "./yr12/Investigating Science/index.jsx";
import Yr12_Investigating_Science_trialpapers_Page84 from "./yr12/Investigating Science/trialpapers.jsx";
import Yr12_IPT_assessment_tasks_Page85 from "./yr12/IPT/assessment-tasks.jsx";
import Yr12_IPT_index_Page86 from "./yr12/IPT/index.jsx";
import Yr12_IPT_trialpapers_Page87 from "./yr12/IPT/trialpapers.jsx";
import Yr12_Legal_Studies_hscpapers_Page88 from "./yr12/Legal Studies/hscpapers.jsx";
import Yr12_Legal_Studies_index_Page89 from "./yr12/Legal Studies/index.jsx";
import Yr12_Legal_Studies_trialpapers_Page90 from "./yr12/Legal Studies/trialpapers.jsx";
import Yr12_LOTE_index_Page91 from "./yr12/LOTE/index.jsx";
import Yr12_LOTE_Japanese_assessment_tasks_continuers_Page92 from "./yr12/LOTE/Japanese/assessment-tasks_continuers.jsx";
import Yr12_LOTE_Japanese_hscpapers_continuers_Page93 from "./yr12/LOTE/Japanese/hscpapers_continuers.jsx";
import Yr12_LOTE_Japanese_hscpapers_extension_Page94 from "./yr12/LOTE/Japanese/hscpapers_extension.jsx";
import Yr12_LOTE_Japanese_index_Page95 from "./yr12/LOTE/Japanese/index.jsx";
import Yr12_LOTE_Japanese_trialpapers_beginners_Page96 from "./yr12/LOTE/Japanese/trialpapers_beginners.jsx";
import Yr12_LOTE_Japanese_trialpapers_continuers_Page97 from "./yr12/LOTE/Japanese/trialpapers_continuers.jsx";
import Yr12_LOTE_Latin_index_Page98 from "./yr12/LOTE/Latin/index.jsx";
import Yr12_LOTE_Latin_trialpapers_continuers_Page99 from "./yr12/LOTE/Latin/trialpapers_continuers.jsx";
import Yr12_LOTE_Latin_trialpapers_extension_Page100 from "./yr12/LOTE/Latin/trialpapers_extension.jsx";
import Yr12_Maths_assessment_tasks_advanced_Page101 from "./yr12/Maths/assessment-tasks_advanced.jsx";
import Yr12_Maths_assessment_tasks_extension1_Page102 from "./yr12/Maths/assessment-tasks_extension1.jsx";
import Yr12_Maths_assessment_tasks_extension2_Page103 from "./yr12/Maths/assessment-tasks_extension2.jsx";
import Yr12_Maths_assessment_tasks_general_Page104 from "./yr12/Maths/assessment-tasks_general.jsx";
import Yr12_Maths_Competitions_cp_apmo_Page105 from "./yr12/Maths/Competitions/cp_apmo.jsx";
import Yr12_Maths_Competitions_cp_balkan_Page106 from "./yr12/Maths/Competitions/cp_balkan.jsx";
import Yr12_Maths_Competitions_cp_cmo_Page107 from "./yr12/Maths/Competitions/cp_cmo.jsx";
import Yr12_Maths_Competitions_cp_imo_Page108 from "./yr12/Maths/Competitions/cp_imo.jsx";
import Yr12_Maths_Competitions_cp_nordic_Page109 from "./yr12/Maths/Competitions/cp_nordic.jsx";
import Yr12_Maths_Competitions_cp_putnam_Page110 from "./yr12/Maths/Competitions/cp_putnam.jsx";
import Yr12_Maths_Competitions_cp_unsw_Page111 from "./yr12/Maths/Competitions/cp_unsw.jsx";
import Yr12_Maths_Competitions_index_Page112 from "./yr12/Maths/Competitions/index.jsx";
import Yr12_Maths_hscpapers_advanced_Page113 from "./yr12/Maths/hscpapers_advanced.jsx";
import Yr12_Maths_hscpapers_extension1_Page114 from "./yr12/Maths/hscpapers_extension1.jsx";
import Yr12_Maths_hscpapers_extension2_Page115 from "./yr12/Maths/hscpapers_extension2.jsx";
import Yr12_Maths_hscpapers_general_Page116 from "./yr12/Maths/hscpapers_general.jsx";
import Yr12_Maths_index_Page117 from "./yr12/Maths/index.jsx";
import Yr12_Maths_trialpapers_advanced_Page118 from "./yr12/Maths/trialpapers_advanced.jsx";
import Yr12_Maths_trialpapers_extension1_Page119 from "./yr12/Maths/trialpapers_extension1.jsx";
import Yr12_Maths_trialpapers_extension2_Page120 from "./yr12/Maths/trialpapers_extension2.jsx";
import Yr12_Maths_trialpapers_general_Page121 from "./yr12/Maths/trialpapers_general.jsx";
import Yr12_Modern_History_hscpapers_Page122 from "./yr12/Modern History/hscpapers.jsx";
import Yr12_Modern_History_index_Page123 from "./yr12/Modern History/index.jsx";
import Yr12_Modern_History_trialpapers_Page124 from "./yr12/Modern History/trialpapers.jsx";
import Yr12_PDHPE_index_Page125 from "./yr12/PDHPE/index.jsx";
import Yr12_PDHPE_trialpapers_Page126 from "./yr12/PDHPE/trialpapers.jsx";
import Yr12_Physics_assessment_tasks_Page127 from "./yr12/Physics/assessment-tasks.jsx";
import Yr12_Physics_hscpapers_Page128 from "./yr12/Physics/hscpapers.jsx";
import Yr12_Physics_index_Page129 from "./yr12/Physics/index.jsx";
import Yr12_Physics_trialpapers_Page130 from "./yr12/Physics/trialpapers.jsx";
import Yr12_Society_Culture_index_Page131 from "./yr12/Society & Culture/index.jsx";
import Yr12_Society_Culture_trialpapers_Page132 from "./yr12/Society & Culture/trialpapers.jsx";
import Yr12_Software_index_Page133 from "./yr12/Software/index.jsx";
import Yr12_Software_trialpapers_Page134 from "./yr12/Software/trialpapers.jsx";
import Yr12_Studies_of_Religion_index_Page135 from "./yr12/Studies of Religion/index.jsx";
import Yr12_Studies_of_Religion_trialpapers_sor1_Page136 from "./yr12/Studies of Religion/trialpapers_sor1.jsx";
import Yr12_Studies_of_Religion_trialpapers_sor2_Page137 from "./yr12/Studies of Religion/trialpapers_sor2.jsx";
import Yr12_Visual_Arts_index_Page138 from "./yr12/Visual Arts/index.jsx";
import Yr12_Visual_Arts_trialpapers_Page139 from "./yr12/Visual Arts/trialpapers.jsx";
import Yr9_index_Page140 from "./yr9/index.jsx";
import Yr9_Maths_assessment_tasks_Page141 from "./yr9/Maths/assessment-tasks.jsx";
import Yr9_Maths_index_Page142 from "./yr9/Maths/index.jsx";
import Yr9_Maths_yr9papers_Page143 from "./yr9/Maths/yr9papers.jsx";

export const routes = [
    {
        path: "/s/yr10/",
        component: Yr10_index_Page3
    },
    {
        path: "/s/yr10/Maths/assessment-tasks.html.html",
        component: Yr10_Maths_assessment_tasks_Page4
    },
    {
        path: "/s/yr10/Maths/",
        component: Yr10_Maths_index_Page5
    },
    {
        path: "/s/yr10/Maths/yr10papers.html.html",
        component: Yr10_Maths_yr10papers_Page6
    },
    {
        path: "/s/yr10/Science/",
        component: Yr10_Science_index_Page7
    },
    {
        path: "/s/yr10/Science/yr10papers.html.html",
        component: Yr10_Science_yr10papers_Page8
    },
    {
        path: "/s/yr11/Biology/assessment-tasks.html.html",
        component: Yr11_Biology_assessment_tasks_Page9
    },
    {
        path: "/s/yr11/Biology/",
        component: Yr11_Biology_index_Page10
    },
    {
        path: "/s/yr11/Biology/prelimpapers.html.html",
        component: Yr11_Biology_prelimpapers_Page11
    },
    {
        path: "/s/yr11/Business Studies/",
        component: Yr11_Business_Studies_index_Page12
    },
    {
        path: "/s/yr11/Business Studies/prelimpapers.html.html",
        component: Yr11_Business_Studies_prelimpapers_Page13
    },
    {
        path: "/s/yr11/Chemistry/assessment-tasks.html.html",
        component: Yr11_Chemistry_assessment_tasks_Page14
    },
    {
        path: "/s/yr11/Chemistry/",
        component: Yr11_Chemistry_index_Page15
    },
    {
        path: "/s/yr11/Chemistry/prelimpapers.html.html",
        component: Yr11_Chemistry_prelimpapers_Page16
    },
    {
        path: "/s/yr11/Earth & Environmental Science/",
        component: Yr11_Earth_Environmental_Science_index_Page17
    },
    {
        path: "/s/yr11/Earth & Environmental Science/prelimpapers.html.html",
        component: Yr11_Earth_Environmental_Science_prelimpapers_Page18
    },
    {
        path: "/s/yr11/Economics/assessment-tasks.html.html",
        component: Yr11_Economics_assessment_tasks_Page19
    },
    {
        path: "/s/yr11/Economics/",
        component: Yr11_Economics_index_Page20
    },
    {
        path: "/s/yr11/Economics/prelimpapers.html.html",
        component: Yr11_Economics_prelimpapers_Page21
    },
    {
        path: "/s/yr11/Engineering Studies/assessment-tasks.html.html",
        component: Yr11_Engineering_Studies_assessment_tasks_Page22
    },
    {
        path: "/s/yr11/Engineering Studies/",
        component: Yr11_Engineering_Studies_index_Page23
    },
    {
        path: "/s/yr11/Engineering Studies/prelimpapers.html.html",
        component: Yr11_Engineering_Studies_prelimpapers_Page24
    },
    {
        path: "/s/yr11/",
        component: Yr11_index_Page25
    },
    {
        path: "/s/yr11/IPT/",
        component: Yr11_IPT_index_Page26
    },
    {
        path: "/s/yr11/IPT/prelimpapers.html.html",
        component: Yr11_IPT_prelimpapers_Page27
    },
    {
        path: "/s/yr11/Legal Studies/",
        component: Yr11_Legal_Studies_index_Page28
    },
    {
        path: "/s/yr11/Legal Studies/prelimpapers.html.html",
        component: Yr11_Legal_Studies_prelimpapers_Page29
    },
    {
        path: "/s/yr11/Maths/assessment-tasks_accelerated.html.html",
        component: Yr11_Maths_assessment_tasks_accelerated_Page30
    },
    {
        path: "/s/yr11/Maths/assessment-tasks_advanced.html.html",
        component: Yr11_Maths_assessment_tasks_advanced_Page31
    },
    {
        path: "/s/yr11/Maths/assessment-tasks_extension1.html.html",
        component: Yr11_Maths_assessment_tasks_extension1_Page32
    },
    {
        path: "/s/yr11/Maths/",
        component: Yr11_Maths_index_Page33
    },
    {
        path: "/s/yr11/Maths/prelimpapers_accelerated.html.html",
        component: Yr11_Maths_prelimpapers_accelerated_Page34
    },
    {
        path: "/s/yr11/Maths/prelimpapers_advanced.html.html",
        component: Yr11_Maths_prelimpapers_advanced_Page35
    },
    {
        path: "/s/yr11/Maths/prelimpapers_extension1.html.html",
        component: Yr11_Maths_prelimpapers_extension1_Page36
    },
    {
        path: "/s/yr11/Maths/prelimpapers_general.html.html",
        component: Yr11_Maths_prelimpapers_general_Page37
    },
    {
        path: "/s/yr11/Modern History/",
        component: Yr11_Modern_History_index_Page38
    },
    {
        path: "/s/yr11/Modern History/prelimpapers.html.html",
        component: Yr11_Modern_History_prelimpapers_Page39
    },
    {
        path: "/s/yr11/Physics/assessment-tasks.html.html",
        component: Yr11_Physics_assessment_tasks_Page40
    },
    {
        path: "/s/yr11/Physics/",
        component: Yr11_Physics_index_Page41
    },
    {
        path: "/s/yr11/Physics/prelimpapers.html.html",
        component: Yr11_Physics_prelimpapers_Page42
    },
    {
        path: "/s/yr12/Agriculture/assessment-tasks.html.html",
        component: Yr12_Agriculture_assessment_tasks_Page43
    },
    {
        path: "/s/yr12/Agriculture/",
        component: Yr12_Agriculture_index_Page44
    },
    {
        path: "/s/yr12/Agriculture/trialpapers.html.html",
        component: Yr12_Agriculture_trialpapers_Page45
    },
    {
        path: "/s/yr12/Ancient History/hscpapers.html.html",
        component: Yr12_Ancient_History_hscpapers_Page46
    },
    {
        path: "/s/yr12/Ancient History/",
        component: Yr12_Ancient_History_index_Page47
    },
    {
        path: "/s/yr12/Ancient History/trialpapers.html.html",
        component: Yr12_Ancient_History_trialpapers_Page48
    },
    {
        path: "/s/yr12/Biology/assessment-tasks.html.html",
        component: Yr12_Biology_assessment_tasks_Page49
    },
    {
        path: "/s/yr12/Biology/hscpapers.html.html",
        component: Yr12_Biology_hscpapers_Page50
    },
    {
        path: "/s/yr12/Biology/",
        component: Yr12_Biology_index_Page51
    },
    {
        path: "/s/yr12/Biology/trialpapers.html.html",
        component: Yr12_Biology_trialpapers_Page52
    },
    {
        path: "/s/yr12/Business Studies/assessment-tasks.html.html",
        component: Yr12_Business_Studies_assessment_tasks_Page53
    },
    {
        path: "/s/yr12/Business Studies/hscpapers.html.html",
        component: Yr12_Business_Studies_hscpapers_Page54
    },
    {
        path: "/s/yr12/Business Studies/",
        component: Yr12_Business_Studies_index_Page55
    },
    {
        path: "/s/yr12/Business Studies/trialpapers.html.html",
        component: Yr12_Business_Studies_trialpapers_Page56
    },
    {
        path: "/s/yr12/Chemistry/assessment-tasks.html.html",
        component: Yr12_Chemistry_assessment_tasks_Page57
    },
    {
        path: "/s/yr12/Chemistry/hscpapers.html.html",
        component: Yr12_Chemistry_hscpapers_Page58
    },
    {
        path: "/s/yr12/Chemistry/",
        component: Yr12_Chemistry_index_Page59
    },
    {
        path: "/s/yr12/Chemistry/trialpapers.html.html",
        component: Yr12_Chemistry_trialpapers_Page60
    },
    {
        path: "/s/yr12/Earth & Environmental Science/hscpapers.html.html",
        component: Yr12_Earth_Environmental_Science_hscpapers_Page61
    },
    {
        path: "/s/yr12/Earth & Environmental Science/",
        component: Yr12_Earth_Environmental_Science_index_Page62
    },
    {
        path: "/s/yr12/Earth & Environmental Science/trialpapers.html.html",
        component: Yr12_Earth_Environmental_Science_trialpapers_Page63
    },
    {
        path: "/s/yr12/Economics/assessment-tasks.html.html",
        component: Yr12_Economics_assessment_tasks_Page64
    },
    {
        path: "/s/yr12/Economics/hscpapers.html.html",
        component: Yr12_Economics_hscpapers_Page65
    },
    {
        path: "/s/yr12/Economics/",
        component: Yr12_Economics_index_Page66
    },
    {
        path: "/s/yr12/Economics/trialpapers.html.html",
        component: Yr12_Economics_trialpapers_Page67
    },
    {
        path: "/s/yr12/Engineering Studies/assessment-tasks.html.html",
        component: Yr12_Engineering_Studies_assessment_tasks_Page68
    },
    {
        path: "/s/yr12/Engineering Studies/hscpapers.html.html",
        component: Yr12_Engineering_Studies_hscpapers_Page69
    },
    {
        path: "/s/yr12/Engineering Studies/",
        component: Yr12_Engineering_Studies_index_Page70
    },
    {
        path: "/s/yr12/Engineering Studies/trialpapers.html.html",
        component: Yr12_Engineering_Studies_trialpapers_Page71
    },
    {
        path: "/s/yr12/English Ext 1/",
        component: Yr12_English_Ext_1_index_Page72
    },
    {
        path: "/s/yr12/English Ext 1/trialpapers_extension1.html.html",
        component: Yr12_English_Ext_1_trialpapers_extension1_Page73
    },
    {
        path: "/s/yr12/English/assessment-tasks.html.html",
        component: Yr12_English_assessment_tasks_Page74
    },
    {
        path: "/s/yr12/English/hscpapers.html.html",
        component: Yr12_English_hscpapers_Page75
    },
    {
        path: "/s/yr12/English/",
        component: Yr12_English_index_Page76
    },
    {
        path: "/s/yr12/English/trialpapers_paper1.html.html",
        component: Yr12_English_trialpapers_paper1_Page77
    },
    {
        path: "/s/yr12/English/trialpapers_paper2_advanced.html.html",
        component: Yr12_English_trialpapers_paper2_advanced_Page78
    },
    {
        path: "/s/yr12/English/trialpapers_paper2_standard.html.html",
        component: Yr12_English_trialpapers_paper2_standard_Page79
    },
    {
        path: "/s/yr12/History Extension/",
        component: Yr12_History_Extension_index_Page80
    },
    {
        path: "/s/yr12/History Extension/trialpapers.html.html",
        component: Yr12_History_Extension_trialpapers_Page81
    },
    {
        path: "/s/yr12/",
        component: Yr12_index_Page82
    },
    {
        path: "/s/yr12/Investigating Science/",
        component: Yr12_Investigating_Science_index_Page83
    },
    {
        path: "/s/yr12/Investigating Science/trialpapers.html.html",
        component: Yr12_Investigating_Science_trialpapers_Page84
    },
    {
        path: "/s/yr12/IPT/assessment-tasks.html.html",
        component: Yr12_IPT_assessment_tasks_Page85
    },
    {
        path: "/s/yr12/IPT/",
        component: Yr12_IPT_index_Page86
    },
    {
        path: "/s/yr12/IPT/trialpapers.html.html",
        component: Yr12_IPT_trialpapers_Page87
    },
    {
        path: "/s/yr12/Legal Studies/hscpapers.html.html",
        component: Yr12_Legal_Studies_hscpapers_Page88
    },
    {
        path: "/s/yr12/Legal Studies/",
        component: Yr12_Legal_Studies_index_Page89
    },
    {
        path: "/s/yr12/Legal Studies/trialpapers.html.html",
        component: Yr12_Legal_Studies_trialpapers_Page90
    },
    {
        path: "/s/yr12/LOTE/",
        component: Yr12_LOTE_index_Page91
    },
    {
        path: "/s/yr12/LOTE/Japanese/assessment-tasks_continuers.html.html",
        component: Yr12_LOTE_Japanese_assessment_tasks_continuers_Page92
    },
    {
        path: "/s/yr12/LOTE/Japanese/hscpapers_continuers.html.html",
        component: Yr12_LOTE_Japanese_hscpapers_continuers_Page93
    },
    {
        path: "/s/yr12/LOTE/Japanese/hscpapers_extension.html.html",
        component: Yr12_LOTE_Japanese_hscpapers_extension_Page94
    },
    {
        path: "/s/yr12/LOTE/Japanese/",
        component: Yr12_LOTE_Japanese_index_Page95
    },
    {
        path: "/s/yr12/LOTE/Japanese/trialpapers_beginners.html.html",
        component: Yr12_LOTE_Japanese_trialpapers_beginners_Page96
    },
    {
        path: "/s/yr12/LOTE/Japanese/trialpapers_continuers.html.html",
        component: Yr12_LOTE_Japanese_trialpapers_continuers_Page97
    },
    {
        path: "/s/yr12/LOTE/Latin/",
        component: Yr12_LOTE_Latin_index_Page98
    },
    {
        path: "/s/yr12/LOTE/Latin/trialpapers_continuers.html.html",
        component: Yr12_LOTE_Latin_trialpapers_continuers_Page99
    },
    {
        path: "/s/yr12/LOTE/Latin/trialpapers_extension.html.html",
        component: Yr12_LOTE_Latin_trialpapers_extension_Page100
    },
    {
        path: "/s/yr12/Maths/assessment-tasks_advanced.html.html",
        component: Yr12_Maths_assessment_tasks_advanced_Page101
    },
    {
        path: "/s/yr12/Maths/assessment-tasks_extension1.html.html",
        component: Yr12_Maths_assessment_tasks_extension1_Page102
    },
    {
        path: "/s/yr12/Maths/assessment-tasks_extension2.html.html",
        component: Yr12_Maths_assessment_tasks_extension2_Page103
    },
    {
        path: "/s/yr12/Maths/assessment-tasks_general.html.html",
        component: Yr12_Maths_assessment_tasks_general_Page104
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_apmo.html.html",
        component: Yr12_Maths_Competitions_cp_apmo_Page105
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_balkan.html.html",
        component: Yr12_Maths_Competitions_cp_balkan_Page106
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_cmo.html.html",
        component: Yr12_Maths_Competitions_cp_cmo_Page107
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_imo.html.html",
        component: Yr12_Maths_Competitions_cp_imo_Page108
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_nordic.html.html",
        component: Yr12_Maths_Competitions_cp_nordic_Page109
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_putnam.html.html",
        component: Yr12_Maths_Competitions_cp_putnam_Page110
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_unsw.html.html",
        component: Yr12_Maths_Competitions_cp_unsw_Page111
    },
    {
        path: "/s/yr12/Maths/Competitions/",
        component: Yr12_Maths_Competitions_index_Page112
    },
    {
        path: "/s/yr12/Maths/hscpapers_advanced.html.html",
        component: Yr12_Maths_hscpapers_advanced_Page113
    },
    {
        path: "/s/yr12/Maths/hscpapers_extension1.html.html",
        component: Yr12_Maths_hscpapers_extension1_Page114
    },
    {
        path: "/s/yr12/Maths/hscpapers_extension2.html.html",
        component: Yr12_Maths_hscpapers_extension2_Page115
    },
    {
        path: "/s/yr12/Maths/hscpapers_general.html.html",
        component: Yr12_Maths_hscpapers_general_Page116
    },
    {
        path: "/s/yr12/Maths/",
        component: Yr12_Maths_index_Page117
    },
    {
        path: "/s/yr12/Maths/trialpapers_advanced.html.html",
        component: Yr12_Maths_trialpapers_advanced_Page118
    },
    {
        path: "/s/yr12/Maths/trialpapers_extension1.html.html",
        component: Yr12_Maths_trialpapers_extension1_Page119
    },
    {
        path: "/s/yr12/Maths/trialpapers_extension2.html.html",
        component: Yr12_Maths_trialpapers_extension2_Page120
    },
    {
        path: "/s/yr12/Maths/trialpapers_general.html.html",
        component: Yr12_Maths_trialpapers_general_Page121
    },
    {
        path: "/s/yr12/Modern History/hscpapers.html.html",
        component: Yr12_Modern_History_hscpapers_Page122
    },
    {
        path: "/s/yr12/Modern History/",
        component: Yr12_Modern_History_index_Page123
    },
    {
        path: "/s/yr12/Modern History/trialpapers.html.html",
        component: Yr12_Modern_History_trialpapers_Page124
    },
    {
        path: "/s/yr12/PDHPE/",
        component: Yr12_PDHPE_index_Page125
    },
    {
        path: "/s/yr12/PDHPE/trialpapers.html.html",
        component: Yr12_PDHPE_trialpapers_Page126
    },
    {
        path: "/s/yr12/Physics/assessment-tasks.html.html",
        component: Yr12_Physics_assessment_tasks_Page127
    },
    {
        path: "/s/yr12/Physics/hscpapers.html.html",
        component: Yr12_Physics_hscpapers_Page128
    },
    {
        path: "/s/yr12/Physics/",
        component: Yr12_Physics_index_Page129
    },
    {
        path: "/s/yr12/Physics/trialpapers.html.html",
        component: Yr12_Physics_trialpapers_Page130
    },
    {
        path: "/s/yr12/Society & Culture/",
        component: Yr12_Society_Culture_index_Page131
    },
    {
        path: "/s/yr12/Society & Culture/trialpapers.html.html",
        component: Yr12_Society_Culture_trialpapers_Page132
    },
    {
        path: "/s/yr12/Software/",
        component: Yr12_Software_index_Page133
    },
    {
        path: "/s/yr12/Software/trialpapers.html.html",
        component: Yr12_Software_trialpapers_Page134
    },
    {
        path: "/s/yr12/Studies of Religion/",
        component: Yr12_Studies_of_Religion_index_Page135
    },
    {
        path: "/s/yr12/Studies of Religion/trialpapers_sor1.html.html",
        component: Yr12_Studies_of_Religion_trialpapers_sor1_Page136
    },
    {
        path: "/s/yr12/Studies of Religion/trialpapers_sor2.html.html",
        component: Yr12_Studies_of_Religion_trialpapers_sor2_Page137
    },
    {
        path: "/s/yr12/Visual Arts/",
        component: Yr12_Visual_Arts_index_Page138
    },
    {
        path: "/s/yr12/Visual Arts/trialpapers.html.html",
        component: Yr12_Visual_Arts_trialpapers_Page139
    },
    {
        path: "/s/yr9/",
        component: Yr9_index_Page140
    },
    {
        path: "/s/yr9/Maths/assessment-tasks.html.html",
        component: Yr9_Maths_assessment_tasks_Page141
    },
    {
        path: "/s/yr9/Maths/",
        component: Yr9_Maths_index_Page142
    },
    {
        path: "/s/yr9/Maths/yr9papers.html.html",
        component: Yr9_Maths_yr9papers_Page143
    }
];
