// AUTO-GENERATED BY sync.ps1
// DO NOT EDIT

import Yr10_index_Page1, {
    title as Yr10_index_Page1Title,
    canonical as Yr10_index_Page1Canonical
} from "./yr10/index.jsx";
import Yr10_Maths_assessment_tasks_Page2, {
    title as Yr10_Maths_assessment_tasks_Page2Title,
    canonical as Yr10_Maths_assessment_tasks_Page2Canonical
} from "./yr10/Maths/assessment-tasks.jsx";
import Yr10_Maths_index_Page3, {
    title as Yr10_Maths_index_Page3Title,
    canonical as Yr10_Maths_index_Page3Canonical
} from "./yr10/Maths/index.jsx";
import Yr10_Maths_yr10papers_Page4, {
    title as Yr10_Maths_yr10papers_Page4Title,
    canonical as Yr10_Maths_yr10papers_Page4Canonical
} from "./yr10/Maths/yr10papers.jsx";
import Yr10_Science_index_Page5, {
    title as Yr10_Science_index_Page5Title,
    canonical as Yr10_Science_index_Page5Canonical
} from "./yr10/Science/index.jsx";
import Yr10_Science_yr10papers_Page6, {
    title as Yr10_Science_yr10papers_Page6Title,
    canonical as Yr10_Science_yr10papers_Page6Canonical
} from "./yr10/Science/yr10papers.jsx";
import Yr11_Biology_assessment_tasks_Page7, {
    title as Yr11_Biology_assessment_tasks_Page7Title,
    canonical as Yr11_Biology_assessment_tasks_Page7Canonical
} from "./yr11/Biology/assessment-tasks.jsx";
import Yr11_Biology_index_Page8, {
    title as Yr11_Biology_index_Page8Title,
    canonical as Yr11_Biology_index_Page8Canonical
} from "./yr11/Biology/index.jsx";
import Yr11_Biology_prelimpapers_Page9, {
    title as Yr11_Biology_prelimpapers_Page9Title,
    canonical as Yr11_Biology_prelimpapers_Page9Canonical
} from "./yr11/Biology/prelimpapers.jsx";
import Yr11_Business_Studies_index_Page10, {
    title as Yr11_Business_Studies_index_Page10Title,
    canonical as Yr11_Business_Studies_index_Page10Canonical
} from "./yr11/Business Studies/index.jsx";
import Yr11_Business_Studies_prelimpapers_Page11, {
    title as Yr11_Business_Studies_prelimpapers_Page11Title,
    canonical as Yr11_Business_Studies_prelimpapers_Page11Canonical
} from "./yr11/Business Studies/prelimpapers.jsx";
import Yr11_Chemistry_assessment_tasks_Page12, {
    title as Yr11_Chemistry_assessment_tasks_Page12Title,
    canonical as Yr11_Chemistry_assessment_tasks_Page12Canonical
} from "./yr11/Chemistry/assessment-tasks.jsx";
import Yr11_Chemistry_index_Page13, {
    title as Yr11_Chemistry_index_Page13Title,
    canonical as Yr11_Chemistry_index_Page13Canonical
} from "./yr11/Chemistry/index.jsx";
import Yr11_Chemistry_prelimpapers_Page14, {
    title as Yr11_Chemistry_prelimpapers_Page14Title,
    canonical as Yr11_Chemistry_prelimpapers_Page14Canonical
} from "./yr11/Chemistry/prelimpapers.jsx";
import Yr11_Earth_Environmental_Science_index_Page15, {
    title as Yr11_Earth_Environmental_Science_index_Page15Title,
    canonical as Yr11_Earth_Environmental_Science_index_Page15Canonical
} from "./yr11/Earth & Environmental Science/index.jsx";
import Yr11_Earth_Environmental_Science_prelimpapers_Page16, {
    title as Yr11_Earth_Environmental_Science_prelimpapers_Page16Title,
    canonical as Yr11_Earth_Environmental_Science_prelimpapers_Page16Canonical
} from "./yr11/Earth & Environmental Science/prelimpapers.jsx";
import Yr11_Economics_assessment_tasks_Page17, {
    title as Yr11_Economics_assessment_tasks_Page17Title,
    canonical as Yr11_Economics_assessment_tasks_Page17Canonical
} from "./yr11/Economics/assessment-tasks.jsx";
import Yr11_Economics_index_Page18, {
    title as Yr11_Economics_index_Page18Title,
    canonical as Yr11_Economics_index_Page18Canonical
} from "./yr11/Economics/index.jsx";
import Yr11_Economics_prelimpapers_Page19, {
    title as Yr11_Economics_prelimpapers_Page19Title,
    canonical as Yr11_Economics_prelimpapers_Page19Canonical
} from "./yr11/Economics/prelimpapers.jsx";
import Yr11_Engineering_Studies_assessment_tasks_Page20, {
    title as Yr11_Engineering_Studies_assessment_tasks_Page20Title,
    canonical as Yr11_Engineering_Studies_assessment_tasks_Page20Canonical
} from "./yr11/Engineering Studies/assessment-tasks.jsx";
import Yr11_Engineering_Studies_index_Page21, {
    title as Yr11_Engineering_Studies_index_Page21Title,
    canonical as Yr11_Engineering_Studies_index_Page21Canonical
} from "./yr11/Engineering Studies/index.jsx";
import Yr11_Engineering_Studies_prelimpapers_Page22, {
    title as Yr11_Engineering_Studies_prelimpapers_Page22Title,
    canonical as Yr11_Engineering_Studies_prelimpapers_Page22Canonical
} from "./yr11/Engineering Studies/prelimpapers.jsx";
import Yr11_index_Page23, {
    title as Yr11_index_Page23Title,
    canonical as Yr11_index_Page23Canonical
} from "./yr11/index.jsx";
import Yr11_IPT_index_Page24, {
    title as Yr11_IPT_index_Page24Title,
    canonical as Yr11_IPT_index_Page24Canonical
} from "./yr11/IPT/index.jsx";
import Yr11_IPT_prelimpapers_Page25, {
    title as Yr11_IPT_prelimpapers_Page25Title,
    canonical as Yr11_IPT_prelimpapers_Page25Canonical
} from "./yr11/IPT/prelimpapers.jsx";
import Yr11_Legal_Studies_index_Page26, {
    title as Yr11_Legal_Studies_index_Page26Title,
    canonical as Yr11_Legal_Studies_index_Page26Canonical
} from "./yr11/Legal Studies/index.jsx";
import Yr11_Legal_Studies_prelimpapers_Page27, {
    title as Yr11_Legal_Studies_prelimpapers_Page27Title,
    canonical as Yr11_Legal_Studies_prelimpapers_Page27Canonical
} from "./yr11/Legal Studies/prelimpapers.jsx";
import Yr11_Maths_assessment_tasks_accelerated_Page28, {
    title as Yr11_Maths_assessment_tasks_accelerated_Page28Title,
    canonical as Yr11_Maths_assessment_tasks_accelerated_Page28Canonical
} from "./yr11/Maths/assessment-tasks_accelerated.jsx";
import Yr11_Maths_assessment_tasks_advanced_Page29, {
    title as Yr11_Maths_assessment_tasks_advanced_Page29Title,
    canonical as Yr11_Maths_assessment_tasks_advanced_Page29Canonical
} from "./yr11/Maths/assessment-tasks_advanced.jsx";
import Yr11_Maths_assessment_tasks_extension1_Page30, {
    title as Yr11_Maths_assessment_tasks_extension1_Page30Title,
    canonical as Yr11_Maths_assessment_tasks_extension1_Page30Canonical
} from "./yr11/Maths/assessment-tasks_extension1.jsx";
import Yr11_Maths_index_Page31, {
    title as Yr11_Maths_index_Page31Title,
    canonical as Yr11_Maths_index_Page31Canonical
} from "./yr11/Maths/index.jsx";
import Yr11_Maths_prelimpapers_accelerated_Page32, {
    title as Yr11_Maths_prelimpapers_accelerated_Page32Title,
    canonical as Yr11_Maths_prelimpapers_accelerated_Page32Canonical
} from "./yr11/Maths/prelimpapers_accelerated.jsx";
import Yr11_Maths_prelimpapers_advanced_Page33, {
    title as Yr11_Maths_prelimpapers_advanced_Page33Title,
    canonical as Yr11_Maths_prelimpapers_advanced_Page33Canonical
} from "./yr11/Maths/prelimpapers_advanced.jsx";
import Yr11_Maths_prelimpapers_extension1_Page34, {
    title as Yr11_Maths_prelimpapers_extension1_Page34Title,
    canonical as Yr11_Maths_prelimpapers_extension1_Page34Canonical
} from "./yr11/Maths/prelimpapers_extension1.jsx";
import Yr11_Maths_prelimpapers_general_Page35, {
    title as Yr11_Maths_prelimpapers_general_Page35Title,
    canonical as Yr11_Maths_prelimpapers_general_Page35Canonical
} from "./yr11/Maths/prelimpapers_general.jsx";
import Yr11_Modern_History_index_Page36, {
    title as Yr11_Modern_History_index_Page36Title,
    canonical as Yr11_Modern_History_index_Page36Canonical
} from "./yr11/Modern History/index.jsx";
import Yr11_Modern_History_prelimpapers_Page37, {
    title as Yr11_Modern_History_prelimpapers_Page37Title,
    canonical as Yr11_Modern_History_prelimpapers_Page37Canonical
} from "./yr11/Modern History/prelimpapers.jsx";
import Yr11_Physics_assessment_tasks_Page38, {
    title as Yr11_Physics_assessment_tasks_Page38Title,
    canonical as Yr11_Physics_assessment_tasks_Page38Canonical
} from "./yr11/Physics/assessment-tasks.jsx";
import Yr11_Physics_index_Page39, {
    title as Yr11_Physics_index_Page39Title,
    canonical as Yr11_Physics_index_Page39Canonical
} from "./yr11/Physics/index.jsx";
import Yr11_Physics_prelimpapers_Page40, {
    title as Yr11_Physics_prelimpapers_Page40Title,
    canonical as Yr11_Physics_prelimpapers_Page40Canonical
} from "./yr11/Physics/prelimpapers.jsx";
import Yr12_Agriculture_assessment_tasks_Page41, {
    title as Yr12_Agriculture_assessment_tasks_Page41Title,
    canonical as Yr12_Agriculture_assessment_tasks_Page41Canonical
} from "./yr12/Agriculture/assessment-tasks.jsx";
import Yr12_Agriculture_index_Page42, {
    title as Yr12_Agriculture_index_Page42Title,
    canonical as Yr12_Agriculture_index_Page42Canonical
} from "./yr12/Agriculture/index.jsx";
import Yr12_Agriculture_trialpapers_Page43, {
    title as Yr12_Agriculture_trialpapers_Page43Title,
    canonical as Yr12_Agriculture_trialpapers_Page43Canonical
} from "./yr12/Agriculture/trialpapers.jsx";
import Yr12_Ancient_History_hscpapers_Page44, {
    title as Yr12_Ancient_History_hscpapers_Page44Title,
    canonical as Yr12_Ancient_History_hscpapers_Page44Canonical
} from "./yr12/Ancient History/hscpapers.jsx";
import Yr12_Ancient_History_index_Page45, {
    title as Yr12_Ancient_History_index_Page45Title,
    canonical as Yr12_Ancient_History_index_Page45Canonical
} from "./yr12/Ancient History/index.jsx";
import Yr12_Ancient_History_trialpapers_Page46, {
    title as Yr12_Ancient_History_trialpapers_Page46Title,
    canonical as Yr12_Ancient_History_trialpapers_Page46Canonical
} from "./yr12/Ancient History/trialpapers.jsx";
import Yr12_Biology_assessment_tasks_Page47, {
    title as Yr12_Biology_assessment_tasks_Page47Title,
    canonical as Yr12_Biology_assessment_tasks_Page47Canonical
} from "./yr12/Biology/assessment-tasks.jsx";
import Yr12_Biology_hscpapers_Page48, {
    title as Yr12_Biology_hscpapers_Page48Title,
    canonical as Yr12_Biology_hscpapers_Page48Canonical
} from "./yr12/Biology/hscpapers.jsx";
import Yr12_Biology_index_Page49, {
    title as Yr12_Biology_index_Page49Title,
    canonical as Yr12_Biology_index_Page49Canonical
} from "./yr12/Biology/index.jsx";
import Yr12_Biology_trialpapers_Page50, {
    title as Yr12_Biology_trialpapers_Page50Title,
    canonical as Yr12_Biology_trialpapers_Page50Canonical
} from "./yr12/Biology/trialpapers.jsx";
import Yr12_Business_Studies_assessment_tasks_Page51, {
    title as Yr12_Business_Studies_assessment_tasks_Page51Title,
    canonical as Yr12_Business_Studies_assessment_tasks_Page51Canonical
} from "./yr12/Business Studies/assessment-tasks.jsx";
import Yr12_Business_Studies_hscpapers_Page52, {
    title as Yr12_Business_Studies_hscpapers_Page52Title,
    canonical as Yr12_Business_Studies_hscpapers_Page52Canonical
} from "./yr12/Business Studies/hscpapers.jsx";
import Yr12_Business_Studies_index_Page53, {
    title as Yr12_Business_Studies_index_Page53Title,
    canonical as Yr12_Business_Studies_index_Page53Canonical
} from "./yr12/Business Studies/index.jsx";
import Yr12_Business_Studies_trialpapers_Page54, {
    title as Yr12_Business_Studies_trialpapers_Page54Title,
    canonical as Yr12_Business_Studies_trialpapers_Page54Canonical
} from "./yr12/Business Studies/trialpapers.jsx";
import Yr12_Chemistry_assessment_tasks_Page55, {
    title as Yr12_Chemistry_assessment_tasks_Page55Title,
    canonical as Yr12_Chemistry_assessment_tasks_Page55Canonical
} from "./yr12/Chemistry/assessment-tasks.jsx";
import Yr12_Chemistry_hscpapers_Page56, {
    title as Yr12_Chemistry_hscpapers_Page56Title,
    canonical as Yr12_Chemistry_hscpapers_Page56Canonical
} from "./yr12/Chemistry/hscpapers.jsx";
import Yr12_Chemistry_index_Page57, {
    title as Yr12_Chemistry_index_Page57Title,
    canonical as Yr12_Chemistry_index_Page57Canonical
} from "./yr12/Chemistry/index.jsx";
import Yr12_Chemistry_trialpapers_Page58, {
    title as Yr12_Chemistry_trialpapers_Page58Title,
    canonical as Yr12_Chemistry_trialpapers_Page58Canonical
} from "./yr12/Chemistry/trialpapers.jsx";
import Yr12_Earth_Environmental_Science_hscpapers_Page59, {
    title as Yr12_Earth_Environmental_Science_hscpapers_Page59Title,
    canonical as Yr12_Earth_Environmental_Science_hscpapers_Page59Canonical
} from "./yr12/Earth & Environmental Science/hscpapers.jsx";
import Yr12_Earth_Environmental_Science_index_Page60, {
    title as Yr12_Earth_Environmental_Science_index_Page60Title,
    canonical as Yr12_Earth_Environmental_Science_index_Page60Canonical
} from "./yr12/Earth & Environmental Science/index.jsx";
import Yr12_Earth_Environmental_Science_trialpapers_Page61, {
    title as Yr12_Earth_Environmental_Science_trialpapers_Page61Title,
    canonical as Yr12_Earth_Environmental_Science_trialpapers_Page61Canonical
} from "./yr12/Earth & Environmental Science/trialpapers.jsx";
import Yr12_Economics_assessment_tasks_Page62, {
    title as Yr12_Economics_assessment_tasks_Page62Title,
    canonical as Yr12_Economics_assessment_tasks_Page62Canonical
} from "./yr12/Economics/assessment-tasks.jsx";
import Yr12_Economics_hscpapers_Page63, {
    title as Yr12_Economics_hscpapers_Page63Title,
    canonical as Yr12_Economics_hscpapers_Page63Canonical
} from "./yr12/Economics/hscpapers.jsx";
import Yr12_Economics_index_Page64, {
    title as Yr12_Economics_index_Page64Title,
    canonical as Yr12_Economics_index_Page64Canonical
} from "./yr12/Economics/index.jsx";
import Yr12_Economics_trialpapers_Page65, {
    title as Yr12_Economics_trialpapers_Page65Title,
    canonical as Yr12_Economics_trialpapers_Page65Canonical
} from "./yr12/Economics/trialpapers.jsx";
import Yr12_Engineering_Studies_assessment_tasks_Page66, {
    title as Yr12_Engineering_Studies_assessment_tasks_Page66Title,
    canonical as Yr12_Engineering_Studies_assessment_tasks_Page66Canonical
} from "./yr12/Engineering Studies/assessment-tasks.jsx";
import Yr12_Engineering_Studies_hscpapers_Page67, {
    title as Yr12_Engineering_Studies_hscpapers_Page67Title,
    canonical as Yr12_Engineering_Studies_hscpapers_Page67Canonical
} from "./yr12/Engineering Studies/hscpapers.jsx";
import Yr12_Engineering_Studies_index_Page68, {
    title as Yr12_Engineering_Studies_index_Page68Title,
    canonical as Yr12_Engineering_Studies_index_Page68Canonical
} from "./yr12/Engineering Studies/index.jsx";
import Yr12_Engineering_Studies_trialpapers_Page69, {
    title as Yr12_Engineering_Studies_trialpapers_Page69Title,
    canonical as Yr12_Engineering_Studies_trialpapers_Page69Canonical
} from "./yr12/Engineering Studies/trialpapers.jsx";
import Yr12_English_Ext_1_index_Page70, {
    title as Yr12_English_Ext_1_index_Page70Title,
    canonical as Yr12_English_Ext_1_index_Page70Canonical
} from "./yr12/English Ext 1/index.jsx";
import Yr12_English_Ext_1_trialpapers_extension1_Page71, {
    title as Yr12_English_Ext_1_trialpapers_extension1_Page71Title,
    canonical as Yr12_English_Ext_1_trialpapers_extension1_Page71Canonical
} from "./yr12/English Ext 1/trialpapers_extension1.jsx";
import Yr12_English_assessment_tasks_Page72, {
    title as Yr12_English_assessment_tasks_Page72Title,
    canonical as Yr12_English_assessment_tasks_Page72Canonical
} from "./yr12/English/assessment-tasks.jsx";
import Yr12_English_hscpapers_Page73, {
    title as Yr12_English_hscpapers_Page73Title,
    canonical as Yr12_English_hscpapers_Page73Canonical
} from "./yr12/English/hscpapers.jsx";
import Yr12_English_index_Page74, {
    title as Yr12_English_index_Page74Title,
    canonical as Yr12_English_index_Page74Canonical
} from "./yr12/English/index.jsx";
import Yr12_English_trialpapers_paper1_Page75, {
    title as Yr12_English_trialpapers_paper1_Page75Title,
    canonical as Yr12_English_trialpapers_paper1_Page75Canonical
} from "./yr12/English/trialpapers_paper1.jsx";
import Yr12_English_trialpapers_paper2_advanced_Page76, {
    title as Yr12_English_trialpapers_paper2_advanced_Page76Title,
    canonical as Yr12_English_trialpapers_paper2_advanced_Page76Canonical
} from "./yr12/English/trialpapers_paper2_advanced.jsx";
import Yr12_English_trialpapers_paper2_standard_Page77, {
    title as Yr12_English_trialpapers_paper2_standard_Page77Title,
    canonical as Yr12_English_trialpapers_paper2_standard_Page77Canonical
} from "./yr12/English/trialpapers_paper2_standard.jsx";
import Yr12_History_Extension_index_Page78, {
    title as Yr12_History_Extension_index_Page78Title,
    canonical as Yr12_History_Extension_index_Page78Canonical
} from "./yr12/History Extension/index.jsx";
import Yr12_History_Extension_trialpapers_Page79, {
    title as Yr12_History_Extension_trialpapers_Page79Title,
    canonical as Yr12_History_Extension_trialpapers_Page79Canonical
} from "./yr12/History Extension/trialpapers.jsx";
import Yr12_index_Page80, {
    title as Yr12_index_Page80Title,
    canonical as Yr12_index_Page80Canonical
} from "./yr12/index.jsx";
import Yr12_Investigating_Science_index_Page81, {
    title as Yr12_Investigating_Science_index_Page81Title,
    canonical as Yr12_Investigating_Science_index_Page81Canonical
} from "./yr12/Investigating Science/index.jsx";
import Yr12_Investigating_Science_trialpapers_Page82, {
    title as Yr12_Investigating_Science_trialpapers_Page82Title,
    canonical as Yr12_Investigating_Science_trialpapers_Page82Canonical
} from "./yr12/Investigating Science/trialpapers.jsx";
import Yr12_IPT_assessment_tasks_Page83, {
    title as Yr12_IPT_assessment_tasks_Page83Title,
    canonical as Yr12_IPT_assessment_tasks_Page83Canonical
} from "./yr12/IPT/assessment-tasks.jsx";
import Yr12_IPT_index_Page84, {
    title as Yr12_IPT_index_Page84Title,
    canonical as Yr12_IPT_index_Page84Canonical
} from "./yr12/IPT/index.jsx";
import Yr12_IPT_trialpapers_Page85, {
    title as Yr12_IPT_trialpapers_Page85Title,
    canonical as Yr12_IPT_trialpapers_Page85Canonical
} from "./yr12/IPT/trialpapers.jsx";
import Yr12_Legal_Studies_hscpapers_Page86, {
    title as Yr12_Legal_Studies_hscpapers_Page86Title,
    canonical as Yr12_Legal_Studies_hscpapers_Page86Canonical
} from "./yr12/Legal Studies/hscpapers.jsx";
import Yr12_Legal_Studies_index_Page87, {
    title as Yr12_Legal_Studies_index_Page87Title,
    canonical as Yr12_Legal_Studies_index_Page87Canonical
} from "./yr12/Legal Studies/index.jsx";
import Yr12_Legal_Studies_trialpapers_Page88, {
    title as Yr12_Legal_Studies_trialpapers_Page88Title,
    canonical as Yr12_Legal_Studies_trialpapers_Page88Canonical
} from "./yr12/Legal Studies/trialpapers.jsx";
import Yr12_LOTE_index_Page89, {
    title as Yr12_LOTE_index_Page89Title,
    canonical as Yr12_LOTE_index_Page89Canonical
} from "./yr12/LOTE/index.jsx";
import Yr12_LOTE_Japanese_assessment_tasks_continuers_Page90, {
    title as Yr12_LOTE_Japanese_assessment_tasks_continuers_Page90Title,
    canonical as Yr12_LOTE_Japanese_assessment_tasks_continuers_Page90Canonical
} from "./yr12/LOTE/Japanese/assessment-tasks_continuers.jsx";
import Yr12_LOTE_Japanese_hscpapers_continuers_Page91, {
    title as Yr12_LOTE_Japanese_hscpapers_continuers_Page91Title,
    canonical as Yr12_LOTE_Japanese_hscpapers_continuers_Page91Canonical
} from "./yr12/LOTE/Japanese/hscpapers_continuers.jsx";
import Yr12_LOTE_Japanese_hscpapers_extension_Page92, {
    title as Yr12_LOTE_Japanese_hscpapers_extension_Page92Title,
    canonical as Yr12_LOTE_Japanese_hscpapers_extension_Page92Canonical
} from "./yr12/LOTE/Japanese/hscpapers_extension.jsx";
import Yr12_LOTE_Japanese_index_Page93, {
    title as Yr12_LOTE_Japanese_index_Page93Title,
    canonical as Yr12_LOTE_Japanese_index_Page93Canonical
} from "./yr12/LOTE/Japanese/index.jsx";
import Yr12_LOTE_Japanese_trialpapers_beginners_Page94, {
    title as Yr12_LOTE_Japanese_trialpapers_beginners_Page94Title,
    canonical as Yr12_LOTE_Japanese_trialpapers_beginners_Page94Canonical
} from "./yr12/LOTE/Japanese/trialpapers_beginners.jsx";
import Yr12_LOTE_Japanese_trialpapers_continuers_Page95, {
    title as Yr12_LOTE_Japanese_trialpapers_continuers_Page95Title,
    canonical as Yr12_LOTE_Japanese_trialpapers_continuers_Page95Canonical
} from "./yr12/LOTE/Japanese/trialpapers_continuers.jsx";
import Yr12_LOTE_Latin_index_Page96, {
    title as Yr12_LOTE_Latin_index_Page96Title,
    canonical as Yr12_LOTE_Latin_index_Page96Canonical
} from "./yr12/LOTE/Latin/index.jsx";
import Yr12_LOTE_Latin_trialpapers_continuers_Page97, {
    title as Yr12_LOTE_Latin_trialpapers_continuers_Page97Title,
    canonical as Yr12_LOTE_Latin_trialpapers_continuers_Page97Canonical
} from "./yr12/LOTE/Latin/trialpapers_continuers.jsx";
import Yr12_LOTE_Latin_trialpapers_extension_Page98, {
    title as Yr12_LOTE_Latin_trialpapers_extension_Page98Title,
    canonical as Yr12_LOTE_Latin_trialpapers_extension_Page98Canonical
} from "./yr12/LOTE/Latin/trialpapers_extension.jsx";
import Yr12_Maths_assessment_tasks_advanced_Page99, {
    title as Yr12_Maths_assessment_tasks_advanced_Page99Title,
    canonical as Yr12_Maths_assessment_tasks_advanced_Page99Canonical
} from "./yr12/Maths/assessment-tasks_advanced.jsx";
import Yr12_Maths_assessment_tasks_extension1_Page100, {
    title as Yr12_Maths_assessment_tasks_extension1_Page100Title,
    canonical as Yr12_Maths_assessment_tasks_extension1_Page100Canonical
} from "./yr12/Maths/assessment-tasks_extension1.jsx";
import Yr12_Maths_assessment_tasks_extension2_Page101, {
    title as Yr12_Maths_assessment_tasks_extension2_Page101Title,
    canonical as Yr12_Maths_assessment_tasks_extension2_Page101Canonical
} from "./yr12/Maths/assessment-tasks_extension2.jsx";
import Yr12_Maths_assessment_tasks_general_Page102, {
    title as Yr12_Maths_assessment_tasks_general_Page102Title,
    canonical as Yr12_Maths_assessment_tasks_general_Page102Canonical
} from "./yr12/Maths/assessment-tasks_general.jsx";
import Yr12_Maths_Competitions_cp_apmo_Page103, {
    title as Yr12_Maths_Competitions_cp_apmo_Page103Title,
    canonical as Yr12_Maths_Competitions_cp_apmo_Page103Canonical
} from "./yr12/Maths/Competitions/cp_apmo.jsx";
import Yr12_Maths_Competitions_cp_balkan_Page104, {
    title as Yr12_Maths_Competitions_cp_balkan_Page104Title,
    canonical as Yr12_Maths_Competitions_cp_balkan_Page104Canonical
} from "./yr12/Maths/Competitions/cp_balkan.jsx";
import Yr12_Maths_Competitions_cp_cmo_Page105, {
    title as Yr12_Maths_Competitions_cp_cmo_Page105Title,
    canonical as Yr12_Maths_Competitions_cp_cmo_Page105Canonical
} from "./yr12/Maths/Competitions/cp_cmo.jsx";
import Yr12_Maths_Competitions_cp_imo_Page106, {
    title as Yr12_Maths_Competitions_cp_imo_Page106Title,
    canonical as Yr12_Maths_Competitions_cp_imo_Page106Canonical
} from "./yr12/Maths/Competitions/cp_imo.jsx";
import Yr12_Maths_Competitions_cp_nordic_Page107, {
    title as Yr12_Maths_Competitions_cp_nordic_Page107Title,
    canonical as Yr12_Maths_Competitions_cp_nordic_Page107Canonical
} from "./yr12/Maths/Competitions/cp_nordic.jsx";
import Yr12_Maths_Competitions_cp_putnam_Page108, {
    title as Yr12_Maths_Competitions_cp_putnam_Page108Title,
    canonical as Yr12_Maths_Competitions_cp_putnam_Page108Canonical
} from "./yr12/Maths/Competitions/cp_putnam.jsx";
import Yr12_Maths_Competitions_cp_unsw_Page109, {
    title as Yr12_Maths_Competitions_cp_unsw_Page109Title,
    canonical as Yr12_Maths_Competitions_cp_unsw_Page109Canonical
} from "./yr12/Maths/Competitions/cp_unsw.jsx";
import Yr12_Maths_Competitions_index_Page110, {
    title as Yr12_Maths_Competitions_index_Page110Title,
    canonical as Yr12_Maths_Competitions_index_Page110Canonical
} from "./yr12/Maths/Competitions/index.jsx";
import Yr12_Maths_hscpapers_advanced_Page111, {
    title as Yr12_Maths_hscpapers_advanced_Page111Title,
    canonical as Yr12_Maths_hscpapers_advanced_Page111Canonical
} from "./yr12/Maths/hscpapers_advanced.jsx";
import Yr12_Maths_hscpapers_extension1_Page112, {
    title as Yr12_Maths_hscpapers_extension1_Page112Title,
    canonical as Yr12_Maths_hscpapers_extension1_Page112Canonical
} from "./yr12/Maths/hscpapers_extension1.jsx";
import Yr12_Maths_hscpapers_extension2_Page113, {
    title as Yr12_Maths_hscpapers_extension2_Page113Title,
    canonical as Yr12_Maths_hscpapers_extension2_Page113Canonical
} from "./yr12/Maths/hscpapers_extension2.jsx";
import Yr12_Maths_hscpapers_general_Page114, {
    title as Yr12_Maths_hscpapers_general_Page114Title,
    canonical as Yr12_Maths_hscpapers_general_Page114Canonical
} from "./yr12/Maths/hscpapers_general.jsx";
import Yr12_Maths_index_Page115, {
    title as Yr12_Maths_index_Page115Title,
    canonical as Yr12_Maths_index_Page115Canonical
} from "./yr12/Maths/index.jsx";
import Yr12_Maths_trialpapers_advanced_Page116, {
    title as Yr12_Maths_trialpapers_advanced_Page116Title,
    canonical as Yr12_Maths_trialpapers_advanced_Page116Canonical
} from "./yr12/Maths/trialpapers_advanced.jsx";
import Yr12_Maths_trialpapers_extension1_Page117, {
    title as Yr12_Maths_trialpapers_extension1_Page117Title,
    canonical as Yr12_Maths_trialpapers_extension1_Page117Canonical
} from "./yr12/Maths/trialpapers_extension1.jsx";
import Yr12_Maths_trialpapers_extension2_Page118, {
    title as Yr12_Maths_trialpapers_extension2_Page118Title,
    canonical as Yr12_Maths_trialpapers_extension2_Page118Canonical
} from "./yr12/Maths/trialpapers_extension2.jsx";
import Yr12_Maths_trialpapers_general_Page119, {
    title as Yr12_Maths_trialpapers_general_Page119Title,
    canonical as Yr12_Maths_trialpapers_general_Page119Canonical
} from "./yr12/Maths/trialpapers_general.jsx";
import Yr12_Modern_History_hscpapers_Page120, {
    title as Yr12_Modern_History_hscpapers_Page120Title,
    canonical as Yr12_Modern_History_hscpapers_Page120Canonical
} from "./yr12/Modern History/hscpapers.jsx";
import Yr12_Modern_History_index_Page121, {
    title as Yr12_Modern_History_index_Page121Title,
    canonical as Yr12_Modern_History_index_Page121Canonical
} from "./yr12/Modern History/index.jsx";
import Yr12_Modern_History_trialpapers_Page122, {
    title as Yr12_Modern_History_trialpapers_Page122Title,
    canonical as Yr12_Modern_History_trialpapers_Page122Canonical
} from "./yr12/Modern History/trialpapers.jsx";
import Yr12_PDHPE_index_Page123, {
    title as Yr12_PDHPE_index_Page123Title,
    canonical as Yr12_PDHPE_index_Page123Canonical
} from "./yr12/PDHPE/index.jsx";
import Yr12_PDHPE_trialpapers_Page124, {
    title as Yr12_PDHPE_trialpapers_Page124Title,
    canonical as Yr12_PDHPE_trialpapers_Page124Canonical
} from "./yr12/PDHPE/trialpapers.jsx";
import Yr12_Physics_assessment_tasks_Page125, {
    title as Yr12_Physics_assessment_tasks_Page125Title,
    canonical as Yr12_Physics_assessment_tasks_Page125Canonical
} from "./yr12/Physics/assessment-tasks.jsx";
import Yr12_Physics_hscpapers_Page126, {
    title as Yr12_Physics_hscpapers_Page126Title,
    canonical as Yr12_Physics_hscpapers_Page126Canonical
} from "./yr12/Physics/hscpapers.jsx";
import Yr12_Physics_index_Page127, {
    title as Yr12_Physics_index_Page127Title,
    canonical as Yr12_Physics_index_Page127Canonical
} from "./yr12/Physics/index.jsx";
import Yr12_Physics_trialpapers_Page128, {
    title as Yr12_Physics_trialpapers_Page128Title,
    canonical as Yr12_Physics_trialpapers_Page128Canonical
} from "./yr12/Physics/trialpapers.jsx";
import Yr12_Society_Culture_index_Page129, {
    title as Yr12_Society_Culture_index_Page129Title,
    canonical as Yr12_Society_Culture_index_Page129Canonical
} from "./yr12/Society & Culture/index.jsx";
import Yr12_Society_Culture_trialpapers_Page130, {
    title as Yr12_Society_Culture_trialpapers_Page130Title,
    canonical as Yr12_Society_Culture_trialpapers_Page130Canonical
} from "./yr12/Society & Culture/trialpapers.jsx";
import Yr12_Software_index_Page131, {
    title as Yr12_Software_index_Page131Title,
    canonical as Yr12_Software_index_Page131Canonical
} from "./yr12/Software/index.jsx";
import Yr12_Software_trialpapers_Page132, {
    title as Yr12_Software_trialpapers_Page132Title,
    canonical as Yr12_Software_trialpapers_Page132Canonical
} from "./yr12/Software/trialpapers.jsx";
import Yr12_Studies_of_Religion_index_Page133, {
    title as Yr12_Studies_of_Religion_index_Page133Title,
    canonical as Yr12_Studies_of_Religion_index_Page133Canonical
} from "./yr12/Studies of Religion/index.jsx";
import Yr12_Studies_of_Religion_trialpapers_sor1_Page134, {
    title as Yr12_Studies_of_Religion_trialpapers_sor1_Page134Title,
    canonical as Yr12_Studies_of_Religion_trialpapers_sor1_Page134Canonical
} from "./yr12/Studies of Religion/trialpapers_sor1.jsx";
import Yr12_Studies_of_Religion_trialpapers_sor2_Page135, {
    title as Yr12_Studies_of_Religion_trialpapers_sor2_Page135Title,
    canonical as Yr12_Studies_of_Religion_trialpapers_sor2_Page135Canonical
} from "./yr12/Studies of Religion/trialpapers_sor2.jsx";
import Yr12_Visual_Arts_index_Page136, {
    title as Yr12_Visual_Arts_index_Page136Title,
    canonical as Yr12_Visual_Arts_index_Page136Canonical
} from "./yr12/Visual Arts/index.jsx";
import Yr12_Visual_Arts_trialpapers_Page137, {
    title as Yr12_Visual_Arts_trialpapers_Page137Title,
    canonical as Yr12_Visual_Arts_trialpapers_Page137Canonical
} from "./yr12/Visual Arts/trialpapers.jsx";
import Yr9_index_Page138, {
    title as Yr9_index_Page138Title,
    canonical as Yr9_index_Page138Canonical
} from "./yr9/index.jsx";
import Yr9_Maths_assessment_tasks_Page139, {
    title as Yr9_Maths_assessment_tasks_Page139Title,
    canonical as Yr9_Maths_assessment_tasks_Page139Canonical
} from "./yr9/Maths/assessment-tasks.jsx";
import Yr9_Maths_index_Page140, {
    title as Yr9_Maths_index_Page140Title,
    canonical as Yr9_Maths_index_Page140Canonical
} from "./yr9/Maths/index.jsx";
import Yr9_Maths_yr9papers_Page141, {
    title as Yr9_Maths_yr9papers_Page141Title,
    canonical as Yr9_Maths_yr9papers_Page141Canonical
} from "./yr9/Maths/yr9papers.jsx";

export const routes = [
    {
        path: "/s/yr10/",
        component: Yr10_index_Page1,
        title: Yr10_index_Page1Title,
        canonical: Yr10_index_Page1Canonical
    },
    {
        path: "/s/yr10/Maths/assessment-tasks.html",
        component: Yr10_Maths_assessment_tasks_Page2,
        title: Yr10_Maths_assessment_tasks_Page2Title,
        canonical: Yr10_Maths_assessment_tasks_Page2Canonical
    },
    {
        path: "/s/yr10/Maths/",
        component: Yr10_Maths_index_Page3,
        title: Yr10_Maths_index_Page3Title,
        canonical: Yr10_Maths_index_Page3Canonical
    },
    {
        path: "/s/yr10/Maths/yr10papers.html",
        component: Yr10_Maths_yr10papers_Page4,
        title: Yr10_Maths_yr10papers_Page4Title,
        canonical: Yr10_Maths_yr10papers_Page4Canonical
    },
    {
        path: "/s/yr10/Science/",
        component: Yr10_Science_index_Page5,
        title: Yr10_Science_index_Page5Title,
        canonical: Yr10_Science_index_Page5Canonical
    },
    {
        path: "/s/yr10/Science/yr10papers.html",
        component: Yr10_Science_yr10papers_Page6,
        title: Yr10_Science_yr10papers_Page6Title,
        canonical: Yr10_Science_yr10papers_Page6Canonical
    },
    {
        path: "/s/yr11/Biology/assessment-tasks.html",
        component: Yr11_Biology_assessment_tasks_Page7,
        title: Yr11_Biology_assessment_tasks_Page7Title,
        canonical: Yr11_Biology_assessment_tasks_Page7Canonical
    },
    {
        path: "/s/yr11/Biology/",
        component: Yr11_Biology_index_Page8,
        title: Yr11_Biology_index_Page8Title,
        canonical: Yr11_Biology_index_Page8Canonical
    },
    {
        path: "/s/yr11/Biology/prelimpapers.html",
        component: Yr11_Biology_prelimpapers_Page9,
        title: Yr11_Biology_prelimpapers_Page9Title,
        canonical: Yr11_Biology_prelimpapers_Page9Canonical
    },
    {
        path: "/s/yr11/Business Studies/",
        component: Yr11_Business_Studies_index_Page10,
        title: Yr11_Business_Studies_index_Page10Title,
        canonical: Yr11_Business_Studies_index_Page10Canonical
    },
    {
        path: "/s/yr11/Business Studies/prelimpapers.html",
        component: Yr11_Business_Studies_prelimpapers_Page11,
        title: Yr11_Business_Studies_prelimpapers_Page11Title,
        canonical: Yr11_Business_Studies_prelimpapers_Page11Canonical
    },
    {
        path: "/s/yr11/Chemistry/assessment-tasks.html",
        component: Yr11_Chemistry_assessment_tasks_Page12,
        title: Yr11_Chemistry_assessment_tasks_Page12Title,
        canonical: Yr11_Chemistry_assessment_tasks_Page12Canonical
    },
    {
        path: "/s/yr11/Chemistry/",
        component: Yr11_Chemistry_index_Page13,
        title: Yr11_Chemistry_index_Page13Title,
        canonical: Yr11_Chemistry_index_Page13Canonical
    },
    {
        path: "/s/yr11/Chemistry/prelimpapers.html",
        component: Yr11_Chemistry_prelimpapers_Page14,
        title: Yr11_Chemistry_prelimpapers_Page14Title,
        canonical: Yr11_Chemistry_prelimpapers_Page14Canonical
    },
    {
        path: "/s/yr11/Earth & Environmental Science/",
        component: Yr11_Earth_Environmental_Science_index_Page15,
        title: Yr11_Earth_Environmental_Science_index_Page15Title,
        canonical: Yr11_Earth_Environmental_Science_index_Page15Canonical
    },
    {
        path: "/s/yr11/Earth & Environmental Science/prelimpapers.html",
        component: Yr11_Earth_Environmental_Science_prelimpapers_Page16,
        title: Yr11_Earth_Environmental_Science_prelimpapers_Page16Title,
        canonical: Yr11_Earth_Environmental_Science_prelimpapers_Page16Canonical
    },
    {
        path: "/s/yr11/Economics/assessment-tasks.html",
        component: Yr11_Economics_assessment_tasks_Page17,
        title: Yr11_Economics_assessment_tasks_Page17Title,
        canonical: Yr11_Economics_assessment_tasks_Page17Canonical
    },
    {
        path: "/s/yr11/Economics/",
        component: Yr11_Economics_index_Page18,
        title: Yr11_Economics_index_Page18Title,
        canonical: Yr11_Economics_index_Page18Canonical
    },
    {
        path: "/s/yr11/Economics/prelimpapers.html",
        component: Yr11_Economics_prelimpapers_Page19,
        title: Yr11_Economics_prelimpapers_Page19Title,
        canonical: Yr11_Economics_prelimpapers_Page19Canonical
    },
    {
        path: "/s/yr11/Engineering Studies/assessment-tasks.html",
        component: Yr11_Engineering_Studies_assessment_tasks_Page20,
        title: Yr11_Engineering_Studies_assessment_tasks_Page20Title,
        canonical: Yr11_Engineering_Studies_assessment_tasks_Page20Canonical
    },
    {
        path: "/s/yr11/Engineering Studies/",
        component: Yr11_Engineering_Studies_index_Page21,
        title: Yr11_Engineering_Studies_index_Page21Title,
        canonical: Yr11_Engineering_Studies_index_Page21Canonical
    },
    {
        path: "/s/yr11/Engineering Studies/prelimpapers.html",
        component: Yr11_Engineering_Studies_prelimpapers_Page22,
        title: Yr11_Engineering_Studies_prelimpapers_Page22Title,
        canonical: Yr11_Engineering_Studies_prelimpapers_Page22Canonical
    },
    {
        path: "/s/yr11/",
        component: Yr11_index_Page23,
        title: Yr11_index_Page23Title,
        canonical: Yr11_index_Page23Canonical
    },
    {
        path: "/s/yr11/IPT/",
        component: Yr11_IPT_index_Page24,
        title: Yr11_IPT_index_Page24Title,
        canonical: Yr11_IPT_index_Page24Canonical
    },
    {
        path: "/s/yr11/IPT/prelimpapers.html",
        component: Yr11_IPT_prelimpapers_Page25,
        title: Yr11_IPT_prelimpapers_Page25Title,
        canonical: Yr11_IPT_prelimpapers_Page25Canonical
    },
    {
        path: "/s/yr11/Legal Studies/",
        component: Yr11_Legal_Studies_index_Page26,
        title: Yr11_Legal_Studies_index_Page26Title,
        canonical: Yr11_Legal_Studies_index_Page26Canonical
    },
    {
        path: "/s/yr11/Legal Studies/prelimpapers.html",
        component: Yr11_Legal_Studies_prelimpapers_Page27,
        title: Yr11_Legal_Studies_prelimpapers_Page27Title,
        canonical: Yr11_Legal_Studies_prelimpapers_Page27Canonical
    },
    {
        path: "/s/yr11/Maths/assessment-tasks_accelerated.html",
        component: Yr11_Maths_assessment_tasks_accelerated_Page28,
        title: Yr11_Maths_assessment_tasks_accelerated_Page28Title,
        canonical: Yr11_Maths_assessment_tasks_accelerated_Page28Canonical
    },
    {
        path: "/s/yr11/Maths/assessment-tasks_advanced.html",
        component: Yr11_Maths_assessment_tasks_advanced_Page29,
        title: Yr11_Maths_assessment_tasks_advanced_Page29Title,
        canonical: Yr11_Maths_assessment_tasks_advanced_Page29Canonical
    },
    {
        path: "/s/yr11/Maths/assessment-tasks_extension1.html",
        component: Yr11_Maths_assessment_tasks_extension1_Page30,
        title: Yr11_Maths_assessment_tasks_extension1_Page30Title,
        canonical: Yr11_Maths_assessment_tasks_extension1_Page30Canonical
    },
    {
        path: "/s/yr11/Maths/",
        component: Yr11_Maths_index_Page31,
        title: Yr11_Maths_index_Page31Title,
        canonical: Yr11_Maths_index_Page31Canonical
    },
    {
        path: "/s/yr11/Maths/prelimpapers_accelerated.html",
        component: Yr11_Maths_prelimpapers_accelerated_Page32,
        title: Yr11_Maths_prelimpapers_accelerated_Page32Title,
        canonical: Yr11_Maths_prelimpapers_accelerated_Page32Canonical
    },
    {
        path: "/s/yr11/Maths/prelimpapers_advanced.html",
        component: Yr11_Maths_prelimpapers_advanced_Page33,
        title: Yr11_Maths_prelimpapers_advanced_Page33Title,
        canonical: Yr11_Maths_prelimpapers_advanced_Page33Canonical
    },
    {
        path: "/s/yr11/Maths/prelimpapers_extension1.html",
        component: Yr11_Maths_prelimpapers_extension1_Page34,
        title: Yr11_Maths_prelimpapers_extension1_Page34Title,
        canonical: Yr11_Maths_prelimpapers_extension1_Page34Canonical
    },
    {
        path: "/s/yr11/Maths/prelimpapers_general.html",
        component: Yr11_Maths_prelimpapers_general_Page35,
        title: Yr11_Maths_prelimpapers_general_Page35Title,
        canonical: Yr11_Maths_prelimpapers_general_Page35Canonical
    },
    {
        path: "/s/yr11/Modern History/",
        component: Yr11_Modern_History_index_Page36,
        title: Yr11_Modern_History_index_Page36Title,
        canonical: Yr11_Modern_History_index_Page36Canonical
    },
    {
        path: "/s/yr11/Modern History/prelimpapers.html",
        component: Yr11_Modern_History_prelimpapers_Page37,
        title: Yr11_Modern_History_prelimpapers_Page37Title,
        canonical: Yr11_Modern_History_prelimpapers_Page37Canonical
    },
    {
        path: "/s/yr11/Physics/assessment-tasks.html",
        component: Yr11_Physics_assessment_tasks_Page38,
        title: Yr11_Physics_assessment_tasks_Page38Title,
        canonical: Yr11_Physics_assessment_tasks_Page38Canonical
    },
    {
        path: "/s/yr11/Physics/",
        component: Yr11_Physics_index_Page39,
        title: Yr11_Physics_index_Page39Title,
        canonical: Yr11_Physics_index_Page39Canonical
    },
    {
        path: "/s/yr11/Physics/prelimpapers.html",
        component: Yr11_Physics_prelimpapers_Page40,
        title: Yr11_Physics_prelimpapers_Page40Title,
        canonical: Yr11_Physics_prelimpapers_Page40Canonical
    },
    {
        path: "/s/yr12/Agriculture/assessment-tasks.html",
        component: Yr12_Agriculture_assessment_tasks_Page41,
        title: Yr12_Agriculture_assessment_tasks_Page41Title,
        canonical: Yr12_Agriculture_assessment_tasks_Page41Canonical
    },
    {
        path: "/s/yr12/Agriculture/",
        component: Yr12_Agriculture_index_Page42,
        title: Yr12_Agriculture_index_Page42Title,
        canonical: Yr12_Agriculture_index_Page42Canonical
    },
    {
        path: "/s/yr12/Agriculture/trialpapers.html",
        component: Yr12_Agriculture_trialpapers_Page43,
        title: Yr12_Agriculture_trialpapers_Page43Title,
        canonical: Yr12_Agriculture_trialpapers_Page43Canonical
    },
    {
        path: "/s/yr12/Ancient History/hscpapers.html",
        component: Yr12_Ancient_History_hscpapers_Page44,
        title: Yr12_Ancient_History_hscpapers_Page44Title,
        canonical: Yr12_Ancient_History_hscpapers_Page44Canonical
    },
    {
        path: "/s/yr12/Ancient History/",
        component: Yr12_Ancient_History_index_Page45,
        title: Yr12_Ancient_History_index_Page45Title,
        canonical: Yr12_Ancient_History_index_Page45Canonical
    },
    {
        path: "/s/yr12/Ancient History/trialpapers.html",
        component: Yr12_Ancient_History_trialpapers_Page46,
        title: Yr12_Ancient_History_trialpapers_Page46Title,
        canonical: Yr12_Ancient_History_trialpapers_Page46Canonical
    },
    {
        path: "/s/yr12/Biology/assessment-tasks.html",
        component: Yr12_Biology_assessment_tasks_Page47,
        title: Yr12_Biology_assessment_tasks_Page47Title,
        canonical: Yr12_Biology_assessment_tasks_Page47Canonical
    },
    {
        path: "/s/yr12/Biology/hscpapers.html",
        component: Yr12_Biology_hscpapers_Page48,
        title: Yr12_Biology_hscpapers_Page48Title,
        canonical: Yr12_Biology_hscpapers_Page48Canonical
    },
    {
        path: "/s/yr12/Biology/",
        component: Yr12_Biology_index_Page49,
        title: Yr12_Biology_index_Page49Title,
        canonical: Yr12_Biology_index_Page49Canonical
    },
    {
        path: "/s/yr12/Biology/trialpapers.html",
        component: Yr12_Biology_trialpapers_Page50,
        title: Yr12_Biology_trialpapers_Page50Title,
        canonical: Yr12_Biology_trialpapers_Page50Canonical
    },
    {
        path: "/s/yr12/Business Studies/assessment-tasks.html",
        component: Yr12_Business_Studies_assessment_tasks_Page51,
        title: Yr12_Business_Studies_assessment_tasks_Page51Title,
        canonical: Yr12_Business_Studies_assessment_tasks_Page51Canonical
    },
    {
        path: "/s/yr12/Business Studies/hscpapers.html",
        component: Yr12_Business_Studies_hscpapers_Page52,
        title: Yr12_Business_Studies_hscpapers_Page52Title,
        canonical: Yr12_Business_Studies_hscpapers_Page52Canonical
    },
    {
        path: "/s/yr12/Business Studies/",
        component: Yr12_Business_Studies_index_Page53,
        title: Yr12_Business_Studies_index_Page53Title,
        canonical: Yr12_Business_Studies_index_Page53Canonical
    },
    {
        path: "/s/yr12/Business Studies/trialpapers.html",
        component: Yr12_Business_Studies_trialpapers_Page54,
        title: Yr12_Business_Studies_trialpapers_Page54Title,
        canonical: Yr12_Business_Studies_trialpapers_Page54Canonical
    },
    {
        path: "/s/yr12/Chemistry/assessment-tasks.html",
        component: Yr12_Chemistry_assessment_tasks_Page55,
        title: Yr12_Chemistry_assessment_tasks_Page55Title,
        canonical: Yr12_Chemistry_assessment_tasks_Page55Canonical
    },
    {
        path: "/s/yr12/Chemistry/hscpapers.html",
        component: Yr12_Chemistry_hscpapers_Page56,
        title: Yr12_Chemistry_hscpapers_Page56Title,
        canonical: Yr12_Chemistry_hscpapers_Page56Canonical
    },
    {
        path: "/s/yr12/Chemistry/",
        component: Yr12_Chemistry_index_Page57,
        title: Yr12_Chemistry_index_Page57Title,
        canonical: Yr12_Chemistry_index_Page57Canonical
    },
    {
        path: "/s/yr12/Chemistry/trialpapers.html",
        component: Yr12_Chemistry_trialpapers_Page58,
        title: Yr12_Chemistry_trialpapers_Page58Title,
        canonical: Yr12_Chemistry_trialpapers_Page58Canonical
    },
    {
        path: "/s/yr12/Earth & Environmental Science/hscpapers.html",
        component: Yr12_Earth_Environmental_Science_hscpapers_Page59,
        title: Yr12_Earth_Environmental_Science_hscpapers_Page59Title,
        canonical: Yr12_Earth_Environmental_Science_hscpapers_Page59Canonical
    },
    {
        path: "/s/yr12/Earth & Environmental Science/",
        component: Yr12_Earth_Environmental_Science_index_Page60,
        title: Yr12_Earth_Environmental_Science_index_Page60Title,
        canonical: Yr12_Earth_Environmental_Science_index_Page60Canonical
    },
    {
        path: "/s/yr12/Earth & Environmental Science/trialpapers.html",
        component: Yr12_Earth_Environmental_Science_trialpapers_Page61,
        title: Yr12_Earth_Environmental_Science_trialpapers_Page61Title,
        canonical: Yr12_Earth_Environmental_Science_trialpapers_Page61Canonical
    },
    {
        path: "/s/yr12/Economics/assessment-tasks.html",
        component: Yr12_Economics_assessment_tasks_Page62,
        title: Yr12_Economics_assessment_tasks_Page62Title,
        canonical: Yr12_Economics_assessment_tasks_Page62Canonical
    },
    {
        path: "/s/yr12/Economics/hscpapers.html",
        component: Yr12_Economics_hscpapers_Page63,
        title: Yr12_Economics_hscpapers_Page63Title,
        canonical: Yr12_Economics_hscpapers_Page63Canonical
    },
    {
        path: "/s/yr12/Economics/",
        component: Yr12_Economics_index_Page64,
        title: Yr12_Economics_index_Page64Title,
        canonical: Yr12_Economics_index_Page64Canonical
    },
    {
        path: "/s/yr12/Economics/trialpapers.html",
        component: Yr12_Economics_trialpapers_Page65,
        title: Yr12_Economics_trialpapers_Page65Title,
        canonical: Yr12_Economics_trialpapers_Page65Canonical
    },
    {
        path: "/s/yr12/Engineering Studies/assessment-tasks.html",
        component: Yr12_Engineering_Studies_assessment_tasks_Page66,
        title: Yr12_Engineering_Studies_assessment_tasks_Page66Title,
        canonical: Yr12_Engineering_Studies_assessment_tasks_Page66Canonical
    },
    {
        path: "/s/yr12/Engineering Studies/hscpapers.html",
        component: Yr12_Engineering_Studies_hscpapers_Page67,
        title: Yr12_Engineering_Studies_hscpapers_Page67Title,
        canonical: Yr12_Engineering_Studies_hscpapers_Page67Canonical
    },
    {
        path: "/s/yr12/Engineering Studies/",
        component: Yr12_Engineering_Studies_index_Page68,
        title: Yr12_Engineering_Studies_index_Page68Title,
        canonical: Yr12_Engineering_Studies_index_Page68Canonical
    },
    {
        path: "/s/yr12/Engineering Studies/trialpapers.html",
        component: Yr12_Engineering_Studies_trialpapers_Page69,
        title: Yr12_Engineering_Studies_trialpapers_Page69Title,
        canonical: Yr12_Engineering_Studies_trialpapers_Page69Canonical
    },
    {
        path: "/s/yr12/English Ext 1/",
        component: Yr12_English_Ext_1_index_Page70,
        title: Yr12_English_Ext_1_index_Page70Title,
        canonical: Yr12_English_Ext_1_index_Page70Canonical
    },
    {
        path: "/s/yr12/English Ext 1/trialpapers_extension1.html",
        component: Yr12_English_Ext_1_trialpapers_extension1_Page71,
        title: Yr12_English_Ext_1_trialpapers_extension1_Page71Title,
        canonical: Yr12_English_Ext_1_trialpapers_extension1_Page71Canonical
    },
    {
        path: "/s/yr12/English/assessment-tasks.html",
        component: Yr12_English_assessment_tasks_Page72,
        title: Yr12_English_assessment_tasks_Page72Title,
        canonical: Yr12_English_assessment_tasks_Page72Canonical
    },
    {
        path: "/s/yr12/English/hscpapers.html",
        component: Yr12_English_hscpapers_Page73,
        title: Yr12_English_hscpapers_Page73Title,
        canonical: Yr12_English_hscpapers_Page73Canonical
    },
    {
        path: "/s/yr12/English/",
        component: Yr12_English_index_Page74,
        title: Yr12_English_index_Page74Title,
        canonical: Yr12_English_index_Page74Canonical
    },
    {
        path: "/s/yr12/English/trialpapers_paper1.html",
        component: Yr12_English_trialpapers_paper1_Page75,
        title: Yr12_English_trialpapers_paper1_Page75Title,
        canonical: Yr12_English_trialpapers_paper1_Page75Canonical
    },
    {
        path: "/s/yr12/English/trialpapers_paper2_advanced.html",
        component: Yr12_English_trialpapers_paper2_advanced_Page76,
        title: Yr12_English_trialpapers_paper2_advanced_Page76Title,
        canonical: Yr12_English_trialpapers_paper2_advanced_Page76Canonical
    },
    {
        path: "/s/yr12/English/trialpapers_paper2_standard.html",
        component: Yr12_English_trialpapers_paper2_standard_Page77,
        title: Yr12_English_trialpapers_paper2_standard_Page77Title,
        canonical: Yr12_English_trialpapers_paper2_standard_Page77Canonical
    },
    {
        path: "/s/yr12/History Extension/",
        component: Yr12_History_Extension_index_Page78,
        title: Yr12_History_Extension_index_Page78Title,
        canonical: Yr12_History_Extension_index_Page78Canonical
    },
    {
        path: "/s/yr12/History Extension/trialpapers.html",
        component: Yr12_History_Extension_trialpapers_Page79,
        title: Yr12_History_Extension_trialpapers_Page79Title,
        canonical: Yr12_History_Extension_trialpapers_Page79Canonical
    },
    {
        path: "/s/yr12/",
        component: Yr12_index_Page80,
        title: Yr12_index_Page80Title,
        canonical: Yr12_index_Page80Canonical
    },
    {
        path: "/s/yr12/Investigating Science/",
        component: Yr12_Investigating_Science_index_Page81,
        title: Yr12_Investigating_Science_index_Page81Title,
        canonical: Yr12_Investigating_Science_index_Page81Canonical
    },
    {
        path: "/s/yr12/Investigating Science/trialpapers.html",
        component: Yr12_Investigating_Science_trialpapers_Page82,
        title: Yr12_Investigating_Science_trialpapers_Page82Title,
        canonical: Yr12_Investigating_Science_trialpapers_Page82Canonical
    },
    {
        path: "/s/yr12/IPT/assessment-tasks.html",
        component: Yr12_IPT_assessment_tasks_Page83,
        title: Yr12_IPT_assessment_tasks_Page83Title,
        canonical: Yr12_IPT_assessment_tasks_Page83Canonical
    },
    {
        path: "/s/yr12/IPT/",
        component: Yr12_IPT_index_Page84,
        title: Yr12_IPT_index_Page84Title,
        canonical: Yr12_IPT_index_Page84Canonical
    },
    {
        path: "/s/yr12/IPT/trialpapers.html",
        component: Yr12_IPT_trialpapers_Page85,
        title: Yr12_IPT_trialpapers_Page85Title,
        canonical: Yr12_IPT_trialpapers_Page85Canonical
    },
    {
        path: "/s/yr12/Legal Studies/hscpapers.html",
        component: Yr12_Legal_Studies_hscpapers_Page86,
        title: Yr12_Legal_Studies_hscpapers_Page86Title,
        canonical: Yr12_Legal_Studies_hscpapers_Page86Canonical
    },
    {
        path: "/s/yr12/Legal Studies/",
        component: Yr12_Legal_Studies_index_Page87,
        title: Yr12_Legal_Studies_index_Page87Title,
        canonical: Yr12_Legal_Studies_index_Page87Canonical
    },
    {
        path: "/s/yr12/Legal Studies/trialpapers.html",
        component: Yr12_Legal_Studies_trialpapers_Page88,
        title: Yr12_Legal_Studies_trialpapers_Page88Title,
        canonical: Yr12_Legal_Studies_trialpapers_Page88Canonical
    },
    {
        path: "/s/yr12/LOTE/",
        component: Yr12_LOTE_index_Page89,
        title: Yr12_LOTE_index_Page89Title,
        canonical: Yr12_LOTE_index_Page89Canonical
    },
    {
        path: "/s/yr12/LOTE/Japanese/assessment-tasks_continuers.html",
        component: Yr12_LOTE_Japanese_assessment_tasks_continuers_Page90,
        title: Yr12_LOTE_Japanese_assessment_tasks_continuers_Page90Title,
        canonical: Yr12_LOTE_Japanese_assessment_tasks_continuers_Page90Canonical
    },
    {
        path: "/s/yr12/LOTE/Japanese/hscpapers_continuers.html",
        component: Yr12_LOTE_Japanese_hscpapers_continuers_Page91,
        title: Yr12_LOTE_Japanese_hscpapers_continuers_Page91Title,
        canonical: Yr12_LOTE_Japanese_hscpapers_continuers_Page91Canonical
    },
    {
        path: "/s/yr12/LOTE/Japanese/hscpapers_extension.html",
        component: Yr12_LOTE_Japanese_hscpapers_extension_Page92,
        title: Yr12_LOTE_Japanese_hscpapers_extension_Page92Title,
        canonical: Yr12_LOTE_Japanese_hscpapers_extension_Page92Canonical
    },
    {
        path: "/s/yr12/LOTE/Japanese/",
        component: Yr12_LOTE_Japanese_index_Page93,
        title: Yr12_LOTE_Japanese_index_Page93Title,
        canonical: Yr12_LOTE_Japanese_index_Page93Canonical
    },
    {
        path: "/s/yr12/LOTE/Japanese/trialpapers_beginners.html",
        component: Yr12_LOTE_Japanese_trialpapers_beginners_Page94,
        title: Yr12_LOTE_Japanese_trialpapers_beginners_Page94Title,
        canonical: Yr12_LOTE_Japanese_trialpapers_beginners_Page94Canonical
    },
    {
        path: "/s/yr12/LOTE/Japanese/trialpapers_continuers.html",
        component: Yr12_LOTE_Japanese_trialpapers_continuers_Page95,
        title: Yr12_LOTE_Japanese_trialpapers_continuers_Page95Title,
        canonical: Yr12_LOTE_Japanese_trialpapers_continuers_Page95Canonical
    },
    {
        path: "/s/yr12/LOTE/Latin/",
        component: Yr12_LOTE_Latin_index_Page96,
        title: Yr12_LOTE_Latin_index_Page96Title,
        canonical: Yr12_LOTE_Latin_index_Page96Canonical
    },
    {
        path: "/s/yr12/LOTE/Latin/trialpapers_continuers.html",
        component: Yr12_LOTE_Latin_trialpapers_continuers_Page97,
        title: Yr12_LOTE_Latin_trialpapers_continuers_Page97Title,
        canonical: Yr12_LOTE_Latin_trialpapers_continuers_Page97Canonical
    },
    {
        path: "/s/yr12/LOTE/Latin/trialpapers_extension.html",
        component: Yr12_LOTE_Latin_trialpapers_extension_Page98,
        title: Yr12_LOTE_Latin_trialpapers_extension_Page98Title,
        canonical: Yr12_LOTE_Latin_trialpapers_extension_Page98Canonical
    },
    {
        path: "/s/yr12/Maths/assessment-tasks_advanced.html",
        component: Yr12_Maths_assessment_tasks_advanced_Page99,
        title: Yr12_Maths_assessment_tasks_advanced_Page99Title,
        canonical: Yr12_Maths_assessment_tasks_advanced_Page99Canonical
    },
    {
        path: "/s/yr12/Maths/assessment-tasks_extension1.html",
        component: Yr12_Maths_assessment_tasks_extension1_Page100,
        title: Yr12_Maths_assessment_tasks_extension1_Page100Title,
        canonical: Yr12_Maths_assessment_tasks_extension1_Page100Canonical
    },
    {
        path: "/s/yr12/Maths/assessment-tasks_extension2.html",
        component: Yr12_Maths_assessment_tasks_extension2_Page101,
        title: Yr12_Maths_assessment_tasks_extension2_Page101Title,
        canonical: Yr12_Maths_assessment_tasks_extension2_Page101Canonical
    },
    {
        path: "/s/yr12/Maths/assessment-tasks_general.html",
        component: Yr12_Maths_assessment_tasks_general_Page102,
        title: Yr12_Maths_assessment_tasks_general_Page102Title,
        canonical: Yr12_Maths_assessment_tasks_general_Page102Canonical
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_apmo.html",
        component: Yr12_Maths_Competitions_cp_apmo_Page103,
        title: Yr12_Maths_Competitions_cp_apmo_Page103Title,
        canonical: Yr12_Maths_Competitions_cp_apmo_Page103Canonical
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_balkan.html",
        component: Yr12_Maths_Competitions_cp_balkan_Page104,
        title: Yr12_Maths_Competitions_cp_balkan_Page104Title,
        canonical: Yr12_Maths_Competitions_cp_balkan_Page104Canonical
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_cmo.html",
        component: Yr12_Maths_Competitions_cp_cmo_Page105,
        title: Yr12_Maths_Competitions_cp_cmo_Page105Title,
        canonical: Yr12_Maths_Competitions_cp_cmo_Page105Canonical
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_imo.html",
        component: Yr12_Maths_Competitions_cp_imo_Page106,
        title: Yr12_Maths_Competitions_cp_imo_Page106Title,
        canonical: Yr12_Maths_Competitions_cp_imo_Page106Canonical
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_nordic.html",
        component: Yr12_Maths_Competitions_cp_nordic_Page107,
        title: Yr12_Maths_Competitions_cp_nordic_Page107Title,
        canonical: Yr12_Maths_Competitions_cp_nordic_Page107Canonical
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_putnam.html",
        component: Yr12_Maths_Competitions_cp_putnam_Page108,
        title: Yr12_Maths_Competitions_cp_putnam_Page108Title,
        canonical: Yr12_Maths_Competitions_cp_putnam_Page108Canonical
    },
    {
        path: "/s/yr12/Maths/Competitions/cp_unsw.html",
        component: Yr12_Maths_Competitions_cp_unsw_Page109,
        title: Yr12_Maths_Competitions_cp_unsw_Page109Title,
        canonical: Yr12_Maths_Competitions_cp_unsw_Page109Canonical
    },
    {
        path: "/s/yr12/Maths/Competitions/",
        component: Yr12_Maths_Competitions_index_Page110,
        title: Yr12_Maths_Competitions_index_Page110Title,
        canonical: Yr12_Maths_Competitions_index_Page110Canonical
    },
    {
        path: "/s/yr12/Maths/hscpapers_advanced.html",
        component: Yr12_Maths_hscpapers_advanced_Page111,
        title: Yr12_Maths_hscpapers_advanced_Page111Title,
        canonical: Yr12_Maths_hscpapers_advanced_Page111Canonical
    },
    {
        path: "/s/yr12/Maths/hscpapers_extension1.html",
        component: Yr12_Maths_hscpapers_extension1_Page112,
        title: Yr12_Maths_hscpapers_extension1_Page112Title,
        canonical: Yr12_Maths_hscpapers_extension1_Page112Canonical
    },
    {
        path: "/s/yr12/Maths/hscpapers_extension2.html",
        component: Yr12_Maths_hscpapers_extension2_Page113,
        title: Yr12_Maths_hscpapers_extension2_Page113Title,
        canonical: Yr12_Maths_hscpapers_extension2_Page113Canonical
    },
    {
        path: "/s/yr12/Maths/hscpapers_general.html",
        component: Yr12_Maths_hscpapers_general_Page114,
        title: Yr12_Maths_hscpapers_general_Page114Title,
        canonical: Yr12_Maths_hscpapers_general_Page114Canonical
    },
    {
        path: "/s/yr12/Maths/",
        component: Yr12_Maths_index_Page115,
        title: Yr12_Maths_index_Page115Title,
        canonical: Yr12_Maths_index_Page115Canonical
    },
    {
        path: "/s/yr12/Maths/trialpapers_advanced.html",
        component: Yr12_Maths_trialpapers_advanced_Page116,
        title: Yr12_Maths_trialpapers_advanced_Page116Title,
        canonical: Yr12_Maths_trialpapers_advanced_Page116Canonical
    },
    {
        path: "/s/yr12/Maths/trialpapers_extension1.html",
        component: Yr12_Maths_trialpapers_extension1_Page117,
        title: Yr12_Maths_trialpapers_extension1_Page117Title,
        canonical: Yr12_Maths_trialpapers_extension1_Page117Canonical
    },
    {
        path: "/s/yr12/Maths/trialpapers_extension2.html",
        component: Yr12_Maths_trialpapers_extension2_Page118,
        title: Yr12_Maths_trialpapers_extension2_Page118Title,
        canonical: Yr12_Maths_trialpapers_extension2_Page118Canonical
    },
    {
        path: "/s/yr12/Maths/trialpapers_general.html",
        component: Yr12_Maths_trialpapers_general_Page119,
        title: Yr12_Maths_trialpapers_general_Page119Title,
        canonical: Yr12_Maths_trialpapers_general_Page119Canonical
    },
    {
        path: "/s/yr12/Modern History/hscpapers.html",
        component: Yr12_Modern_History_hscpapers_Page120,
        title: Yr12_Modern_History_hscpapers_Page120Title,
        canonical: Yr12_Modern_History_hscpapers_Page120Canonical
    },
    {
        path: "/s/yr12/Modern History/",
        component: Yr12_Modern_History_index_Page121,
        title: Yr12_Modern_History_index_Page121Title,
        canonical: Yr12_Modern_History_index_Page121Canonical
    },
    {
        path: "/s/yr12/Modern History/trialpapers.html",
        component: Yr12_Modern_History_trialpapers_Page122,
        title: Yr12_Modern_History_trialpapers_Page122Title,
        canonical: Yr12_Modern_History_trialpapers_Page122Canonical
    },
    {
        path: "/s/yr12/PDHPE/",
        component: Yr12_PDHPE_index_Page123,
        title: Yr12_PDHPE_index_Page123Title,
        canonical: Yr12_PDHPE_index_Page123Canonical
    },
    {
        path: "/s/yr12/PDHPE/trialpapers.html",
        component: Yr12_PDHPE_trialpapers_Page124,
        title: Yr12_PDHPE_trialpapers_Page124Title,
        canonical: Yr12_PDHPE_trialpapers_Page124Canonical
    },
    {
        path: "/s/yr12/Physics/assessment-tasks.html",
        component: Yr12_Physics_assessment_tasks_Page125,
        title: Yr12_Physics_assessment_tasks_Page125Title,
        canonical: Yr12_Physics_assessment_tasks_Page125Canonical
    },
    {
        path: "/s/yr12/Physics/hscpapers.html",
        component: Yr12_Physics_hscpapers_Page126,
        title: Yr12_Physics_hscpapers_Page126Title,
        canonical: Yr12_Physics_hscpapers_Page126Canonical
    },
    {
        path: "/s/yr12/Physics/",
        component: Yr12_Physics_index_Page127,
        title: Yr12_Physics_index_Page127Title,
        canonical: Yr12_Physics_index_Page127Canonical
    },
    {
        path: "/s/yr12/Physics/trialpapers.html",
        component: Yr12_Physics_trialpapers_Page128,
        title: Yr12_Physics_trialpapers_Page128Title,
        canonical: Yr12_Physics_trialpapers_Page128Canonical
    },
    {
        path: "/s/yr12/Society & Culture/",
        component: Yr12_Society_Culture_index_Page129,
        title: Yr12_Society_Culture_index_Page129Title,
        canonical: Yr12_Society_Culture_index_Page129Canonical
    },
    {
        path: "/s/yr12/Society & Culture/trialpapers.html",
        component: Yr12_Society_Culture_trialpapers_Page130,
        title: Yr12_Society_Culture_trialpapers_Page130Title,
        canonical: Yr12_Society_Culture_trialpapers_Page130Canonical
    },
    {
        path: "/s/yr12/Software/",
        component: Yr12_Software_index_Page131,
        title: Yr12_Software_index_Page131Title,
        canonical: Yr12_Software_index_Page131Canonical
    },
    {
        path: "/s/yr12/Software/trialpapers.html",
        component: Yr12_Software_trialpapers_Page132,
        title: Yr12_Software_trialpapers_Page132Title,
        canonical: Yr12_Software_trialpapers_Page132Canonical
    },
    {
        path: "/s/yr12/Studies of Religion/",
        component: Yr12_Studies_of_Religion_index_Page133,
        title: Yr12_Studies_of_Religion_index_Page133Title,
        canonical: Yr12_Studies_of_Religion_index_Page133Canonical
    },
    {
        path: "/s/yr12/Studies of Religion/trialpapers_sor1.html",
        component: Yr12_Studies_of_Religion_trialpapers_sor1_Page134,
        title: Yr12_Studies_of_Religion_trialpapers_sor1_Page134Title,
        canonical: Yr12_Studies_of_Religion_trialpapers_sor1_Page134Canonical
    },
    {
        path: "/s/yr12/Studies of Religion/trialpapers_sor2.html",
        component: Yr12_Studies_of_Religion_trialpapers_sor2_Page135,
        title: Yr12_Studies_of_Religion_trialpapers_sor2_Page135Title,
        canonical: Yr12_Studies_of_Religion_trialpapers_sor2_Page135Canonical
    },
    {
        path: "/s/yr12/Visual Arts/",
        component: Yr12_Visual_Arts_index_Page136,
        title: Yr12_Visual_Arts_index_Page136Title,
        canonical: Yr12_Visual_Arts_index_Page136Canonical
    },
    {
        path: "/s/yr12/Visual Arts/trialpapers.html",
        component: Yr12_Visual_Arts_trialpapers_Page137,
        title: Yr12_Visual_Arts_trialpapers_Page137Title,
        canonical: Yr12_Visual_Arts_trialpapers_Page137Canonical
    },
    {
        path: "/s/yr9/",
        component: Yr9_index_Page138,
        title: Yr9_index_Page138Title,
        canonical: Yr9_index_Page138Canonical
    },
    {
        path: "/s/yr9/Maths/assessment-tasks.html",
        component: Yr9_Maths_assessment_tasks_Page139,
        title: Yr9_Maths_assessment_tasks_Page139Title,
        canonical: Yr9_Maths_assessment_tasks_Page139Canonical
    },
    {
        path: "/s/yr9/Maths/",
        component: Yr9_Maths_index_Page140,
        title: Yr9_Maths_index_Page140Title,
        canonical: Yr9_Maths_index_Page140Canonical
    },
    {
        path: "/s/yr9/Maths/yr9papers.html",
        component: Yr9_Maths_yr9papers_Page141,
        title: Yr9_Maths_yr9papers_Page141Title,
        canonical: Yr9_Maths_yr9papers_Page141Canonical
    }
];
