// AUTO-GENERATED BY sync.ps1
// Source: yr12\LOTE\Latin\index.html

export const title = "THSC Online - HSC Latin Resources";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;    
<a href="/s/yr12/LOTE">Languages →</a>&nbsp;    
<a className="current" href="/s/yr12/LOTE/Latin">Latin →</a>&nbsp;    
<a className="reverse" href="../">↖ [<i>Up One Folder</i>]</a>    
</div></div>
<div id="content-all">
<h3><span className="title"><img src="/s/images/colours/icon_cloudy.png" />&nbsp;&nbsp;HSC Latin Resources</span></h3>
<div id="web-list">
<div><div><div>
<details className="smallscreen" style={{ display: 'none' }}><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png" />&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../../">Back to Year 12 - HSC</a></span><br /><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../">Back to HSC Languages</a></span><br /><br />

</details>
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="trialpapers_continuers.html">Latin Continuers Trial Papers</a><br />
<span style={{ paddingLeft: '29px' }}>1 papers online (no listening audio)</span></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="trialpapers_extension.html">Latin Extension Trial Papers</a><br />
<span style={{ paddingLeft: '29px' }}>1 papers online (no listening audio)</span></span><br />
<br />
</div></div></div></div>
</div>
        </>
    );
}
