// AUTO-GENERATED BY sync.ps1
// Source: yr12\LOTE\Latin\trialpapers_continuers.html

export const title = "THSC Online - HSC Latin Continuers Trial Papers";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;
<a href="/s/yr12/LOTE/">Languages →</a>&nbsp;
<a href="/s/yr12/LOTE/Latin/">Latin Continuers →</a>&nbsp;
<a className="current" href="/s/yr12/LOTE/Latin/trialpapers_continuers.html">Past Trials →</a>&nbsp;
<a className="reverse" href="index.html">↖ [<i>Up One Folder</i>]</a>
</div></div>
<div id="content-all">
<h4>HSC Latin Continuers Trial Papers</h4>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png">&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br>
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="../">Back to Year 12 - HSC</a></span><br>
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="index.html">Up One Folder</a></span><br><br>
</details>
<table className="listing" id="papers-by-school"><tbody>
<tr className="content"><td>
<ul>
<li>Sample answers or marking guidelines included with most papers.</li>
<li>To contribute past papers or other practice questions, <a href="/s/upload">upload files here</a></li>
</ul></td></tr>
<tr><td>James Ruse<br>
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4643)}>James Ruse 2021</a><br>
</span></td></tr>
</tbody></table>
</div>
        </>
    );
}
