// AUTO-GENERATED BY sync.ps1
// Source: yr12\Maths\index.html

export const title = "THSC Online - HSC Maths Resources";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;    
<a className="current" href="/s/yr12/Maths/">Maths →</a>&nbsp;    
<a className="reverse" href="../">↖ [<i>Up One Folder</i>]</a>    
</div></div>
<div id="content-all">
<h3><span className="title"><img src="/s/images/colours/icon_red.png" />&nbsp;&nbsp;HSC Maths Resources</span></h3>
<div id="web-list">
<div><div><div>
<details className="smallscreen" style={{ display: 'none' }}><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png" />&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../">Back to Year 12 - HSC</a></span><br /><br />
</details>
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="hscpapers_general.html">General / Standard Maths HSC Papers</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="hscpapers_advanced.html">Maths (2U) HSC Papers</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="hscpapers_extension1.html">Maths Ext 1 HSC Papers</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="hscpapers_extension2.html">Maths Ext 2 HSC Papers</a></span><br />
<br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="trialpapers_general.html">General / Standard Maths Trial Papers</a><br />
<span style={{ paddingLeft: '29px' }}>190 papers online, 174 w. sol</span></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="trialpapers_advanced.html">Maths (2U) Trial Papers</a><br />
<span style={{ paddingLeft: '29px' }}>699 papers online, 662 w. sol</span></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="trialpapers_extension1.html">Maths Ext 1 Trial Papers</a><br />
<span style={{ paddingLeft: '29px' }}>810 papers online, 754 w. sol</span></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="trialpapers_extension2.html">Maths Ext 2 Trial Papers</a><br />
<span style={{ paddingLeft: '29px' }}>721,papers online, 617 w. sol</span></span><br />
<br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="assessment-tasks_general.html">General / Standard Maths Internal Assessment Tasks</a><br />
<span style={{ paddingLeft: '29px' }}>35 papers online, 23 w. sol</span></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="assessment-tasks_advanced.html">Maths (2U) Internal Assessment Tasks</a><br />
<span style={{ paddingLeft: '29px' }}>397 papers online, 363 w. sol</span></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="assessment-tasks_extension1.html">Maths Ext 1 Internal Assessment Tasks</a><br />
<span style={{ paddingLeft: '29px' }}>544 papers online, 497 w. sol</span></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="assessment-tasks_extension2.html">Maths Ext 2 Internal Assessment Tasks</a><br />
<span style={{ paddingLeft: '29px' }}>558 papers online, 502 w. sol</span></span><br />
<br />

<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="Competitions/">Competitions</a></span><br />

<h4>Other Links/Resources</h4>
<span><img src="/s/images/icon_link.png" />&nbsp;&nbsp;
<a href="https://4unitmaths.com/me2.html" target="_blank">Angelfire 4U Maths Site</a></span><br />
</div></div></div></div>
</div>
        </>
    );
}
