// AUTO-GENERATED BY sync.ps1
// Source: yr12\LOTE\Japanese\index.html

export const title = "THSC Online - HSC Japanese Resources";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;    
<a href="/s/yr12/LOTE">Languages →</a>&nbsp;    
<a className="current" href="/s/yr12/LOTE/Japanese">Japanese →</a>&nbsp;    
<a className="reverse" href="../">↖ [<i>Up One Folder</i>]</a>    
</div></div>
<div id="content-all">
<h3><span className="title"><img src="/s/images/colours/icon_pink.png" />&nbsp;&nbsp;HSC Japanese Resources</span></h3>
<div id="web-list">
<div><div><div>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png" />&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../../">Back to Year 12 - HSC</a></span><br /><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../">Back to HSC Languages</a></span><br /><br />

</details>
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="hscpapers_continuers.html">Japanese Continuers HSC Papers</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="hscpapers_extension.html">Japanese Extension HSC Papers</a></span><br />
<br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="sacepapers_continuers.html">Japanese Continuers SACE (South Australia) Papers</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="vcepapers_continuers.html">Japanese SL VCE (Victoria) Papers</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="wacepapers_continuers.html">Japanese SL WACE (Western Australia) Papers</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="tcepapers_continuers.html">Japanese TCE (Tasmania) Papers</a></span><br />
<br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="trialpapers_beginners.html">Japanese Beginners Trial Papers</a><br />
<span style="padding-left:29px;">3 papers online (no listening audio)</span></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="trialpapers_continuers.html">Japanese Continuers Trial Papers</a><br />
<span style="padding-left:29px;">3 papers online (no listening audio)</span></span><br />
<br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="assessment-tasks_continuers.html">Japanese Continuers Internal Assessment Tasks</a><br />
<span style="padding-left:29px;">4 papers online, 1 w. sol (no listening audio)</span></span><br />
<br />
<span><img src="/s/images/icon_pdf2.png" />&nbsp;&nbsp;
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4600)}>Japanese Kanji Booklet</a></span><br />
<span><img src="/s/images/icon_pdf2.png" />&nbsp;&nbsp;
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4600)}>Japanese Skills Booklet</a></span><br />
<span><img src="/s/images/icon_pdf2.png" />&nbsp;&nbsp;
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4600)}>Japanese Speaking Tips</a></span><br />
</div></div></div></div>
</div>
        </>
    );
}
