// AUTO-GENERATED BY sync.ps1
// Source: upload\index.html

export const title = "THSC Online - Upload Files";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="element"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="current reducible"><a href="/s/upload/">Upload Files</a></li>
<li className="element reducible"><a href="/s/fz/">Frenzy</a></li></ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a className="current" href="/s/upload/">Upload Files →</a>&nbsp;
<a className="reverse" href="../">↖ [<i>Up One Folder</i>]</a>    
</div></div>
<div id="content-all">
<h3><span className="title">Upload Files</span></h3>
<div id="web-list">
<div><div><div>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png">&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<br />
</details>
All submissions of past papers or practice questions (TEX/PDF files preferred) are welcome.<br /><br />

<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSdvUNKUsrj_1GRCvu7izKoTQJOck57HAfCY62cbSnPTDiYm7A/viewform">Upload Files Here</a><br /><br />
<a target="_blank" href="https://github.com/thsconline/s/issues">Report an Issue with any of the HTML pages here</a><br /><br />
<a href="mailto:thsconline@gmail.com">Feedback and Suggestions</a><br /><br />
<b>Note: </b>If uploading multiple files, create a google drive folder and email the link to thsconline@gmail.com
</div></div></div></div> 
</div>
        </>
    );
}
