// AUTO-GENERATED BY sync.ps1
// Source: upload\uploader.html

export const title = "thsconline (loading...)";

export default function Page() {
    return (
        <>
<body>
<script> var ua = window.navigator.userAgent; var msie = ua.indexOf("MSIE ");
if (msie > 0){var version=parseInt(ua.substring(msie + 5, ua.indexOf(".", msie)));
if(version>9){window.location="https://script.google.com/macros/s/AKfycbzF1ydtQ_i2DefJv_OZ2jbYCav4HQTChR8Ya4LU4QUPkDpQ1QlX/exec#script_frame";}
else {document.write("&nbsp;&nbsp;Redirect Failed. This browser does not support Google Scripts <a href='index.html' className='x'>Back</a>");}}
else {window.location="https://script.google.com/macros/s/AKfycbzF1ydtQ_i2DefJv_OZ2jbYCav4HQTChR8Ya4LU4QUPkDpQ1QlX/exec#script_frame";}
</script>
        </>
    );
}
