// AUTO-GENERATED BY sync.ps1
// Source: yr12\Engineering Studies\index.html

export const title = "THSC Online - HSC Engineering Studies Resources";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;
<a className="current" href="/s/yr12/Engineering Studies/">Engineering Studies →</a>&nbsp;
<a className="reverse" href="../">↖ [<i>Up One Folder</i>]</a>
</div></div>
<div id="content-all">
<h3><span className="title"><img src="/s/images/colours/icon_aqua.png" />&nbsp;&nbsp;HSC Engineering Studies Resources</span></h3>
<div id="web-list">
<div><div><div>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png" />&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../">Back to Year 12 - HSC</a></span><br />
</details>
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="hscpapers.html">Engineering Studies HSC Papers</a></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="trialpapers.html">Engineering Studies Trial Papers</a><br />
<span style="padding-left: 29px;">3 papers online, 1 w. sol</span></span><br />
<span><img src="/s/images/icon_folder.png" />&nbsp;&nbsp;
<a href="assessment-tasks.html">Engineering Studies Internal Assessment Tasks</a><br />
<span style="padding-left: 29px;">3 papers online, 1 w. sol</span></span><br />
</div></div></div></div>
</div>
        </>
    );
}
