// AUTO-GENERATED BY sync.ps1
// Source: yr12\Earth & Environmental Science\index.html

export const title = "THSC Online - HSC Earth &amp; Environmental Science Resources";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;
<a className="current" href="/s/yr12/Earth &amp; Environmental Science/">Earth &amp; Environmental Science →</a>&nbsp;
<a className="reverse" href="../">↖ [<i>Up One Folder</i>]</a>
</div></div>
<div id="content-all">
<h3><span className="title"><img src="/s/images/colours/icon_purple.png">&nbsp;&nbsp;HSC Earth &amp; Environmental Science Resources</span></h3>
<div id="web-list">
<div><div><div>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png">&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="../">Back to Year 12 - HSC</a></span><br />
</details>
<span><img src="/s/images/icon_folder.png">&nbsp;&nbsp;
<a href="hscpapers.html">Earth &amp; Environmental Science HSC Papers</a></span><br />
<span><img src="/s/images/icon_folder.png">&nbsp;&nbsp;
<a href="trialpapers.html">Earth &amp; Environmental Science Trial Papers</a><br />
<span style="padding-left:29px;">11 papers online, 4 w. sol</span></span><br />
</div></div></div></div>
</div>
        </>
    );
}
