// AUTO-GENERATED BY sync.ps1
// Source: yr11\Maths\index.html

export const title = "THSC Online - Year 11 Maths Resources";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="current"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="element"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr11/">Year 11 - Preliminary →</a>&nbsp;
<a className="current" href="/s/yr11/Maths/">Maths →</a>&nbsp;
<a className="reverse" href="../">↖ [<i>Up One Folder</i>]</a>
</div></div>
<div id="content-all">
<h3><span className="title"><img src="/s/images/colours/icon_red.png">&nbsp;&nbsp;Year 11 Maths Resources</span></h3>
<div id="web-list">
<div><div><div>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png">&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br>
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="../">Back to Year 11 - Preliminary</a></span><br>
</details>
<span><img src="/s/images/icon_folder.png">&nbsp;&nbsp;
<a href="prelimpapers_general.html">General Maths Year 11 Yearly Papers </a><br>
<span style="padding-left:29px;">15 papers online, 9 w. sol</span></span><br>
<span><img src="/s/images/icon_folder.png">&nbsp;&nbsp;
<a href="prelimpapers_advanced.html">Maths (2U) Year 11 Yearly Papers </a><br>
<span style="padding-left: 29px;">291 papers online, 262 w. sol</span></span><br>
<span><img src="/s/images/icon_folder.png">&nbsp;&nbsp;
<a href="prelimpapers_accelerated.html">Maths Accelerated Year 11 Yearly Papers </a><br>
<span style="padding-left:29px;">13 papers online, 13 w. sol</span></span><br>
<span><img src="/s/images/icon_folder.png">&nbsp;&nbsp;
<a href="prelimpapers_extension1.html">Maths Ext 1 Year 11 Yearly Papers </a><br>
<span style="padding-left: 29px;">252 papers online, 225 w. sol</span></span><br>
<br>
<span><img src="/s/images/icon_folder.png">&nbsp;&nbsp;
<a href="assessment-tasks_advanced.html">Maths (2U) Internal Assessment Tasks</a><br>
<span style="padding-left:29px;">228 papers online, 215 w. sol</span></span><br>
<span><img src="/s/images/icon_folder.png">&nbsp;&nbsp;
<a href="assessment-tasks_accelerated.html">Maths Accelerated Internal Assessment Tasks</a><br>
<span style="padding-left:29px;">6 papers online, 5 w. sol</span></span><br>
<span><img src="/s/images/icon_folder.png">&nbsp;&nbsp;
<a href="assessment-tasks_extension1.html">Maths Ext 1 Internal Assessment Tasks</a><br>
<span style="padding-left:29px;">215 papers online, 191 w. sol</span></span><br>
</div></div></div></div>
</div>
        </>
    );
}
