// AUTO-GENERATED BY sync.ps1
// Source: yr12\Chemistry\assessment-tasks.html

export const title = "THSC Online - HSC Chemistry Assessment Tasks";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;
<a href="/s/yr12/Chemistry/">Chemistry →</a>&nbsp;
<a className="current" href="/s/yr12/Chemistry/assessment-tasks.html">Past Assessment Tasks →</a>&nbsp;
<a className="reverse" href="index.html">↖ [<i>Up One Folder</i>]</a>
</div></div>  
<div id="content-all">
<h4>HSC Chemistry Assessment Tasks</h4>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png">&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br>
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="../">Back to Year 12 - HSC</a></span><br>
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="index.html">Up One Folder</a></span><br><br>
</details>
<table className="listing" id="papers-by-school"><tbody>
<tr className="content"><td><span style="color:#0000FF;"><b>Note: </b></span>Some materials listed are from old syllabus prescriptions.</td></tr>
<tr className="content"><td><span style="color:#0000FF;"><b>Note 2: </b></span>2021 exams were conducted online, so the format of materials listed may differ slightly.</td></tr>
<tr className="content"><td>
<ul>
<li>Sample answers or marking guidelines included with most papers.</li>
<li>To contribute past papers or other practice questions, <a href="/s/upload">upload files here</a></li>
</ul></td></tr>
<tr><td><h5 id="half-yearly-exams">Half-Yearly Exams</h5></td></tr>

<tr><td><details open><summary>Ascham</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Ascham 2016 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Barker</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Barker 2006 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Barker 2007 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Cheltenham Girls</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Cheltenham Girls 2009 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Cheltenham Girls 2010 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Cherrybrook Tech</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Cherrybrook Tech 2012</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Cherrybrook Tech 2013</a>
</span></details></td></tr>
<tr><td><details open><summary>Cranbrook</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Cranbrook 2008</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Cranbrook 2009</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Cranbrook 2012</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Cranbrook 2013</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Cranbrook 2014</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Cranbrook 2015</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Cranbrook 2017 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Cranbrook 2019 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Hurlstone</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Hurlstone 2004</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Hurlstone 2005</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Hurlstone 2006 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Hurlstone 2007 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Hurlstone 2008 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Hurlstone 2009 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Hurlstone 2010 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Hurlstone 2011 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Hurlstone 2012 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>James Ruse</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2001</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2002 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2003 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2004 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2005 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2006 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2007 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2008 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2009 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2010 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2011 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2012 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2013 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2014 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2015 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2016 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>James Ruse 2019 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Killara</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Killara 2016 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Knox</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Knox 2001</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Knox 2006</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Knox 2007 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Knox 2008 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Presbyterian</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Presbyterian 2001</a>
</span></details></td></tr>
<tr><td><details open><summary>Sydney Girls</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Sydney Girls 2002</a>
</span></details></td></tr>
<tr><td><details open><summary>Trinity Grammar</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1826)}>Trinity Grammar 2010</a>
</span></details></td></tr>

<tr><td><h5 id="task-1-exams">CT1 Nov-Dec Assessments</h5></td></tr>
<tr className="content"><td>Typically Task 1 exams held in Term 4.<br> <span style="color:#0000FF;"><b>Note: </b></span> The year listed is that which the paper was held not the graduating HSC year</td></tr>
<tr><td>&nbsp;</td></tr>

<tr><td><details open><summary>Abbotsleigh</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Abbotsleigh 2025</a>
</span></details></td></tr>
<tr><td><details open><summary>Hornsby Girls</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Hornsby Girls 2020</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Hornsby Girls 2021</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Hornsby Girls 2022</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Hornsby Girls 2023</a>
</span></details></td></tr>
<tr><td><details open><summary>Hurlstone</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Hurlstone 2004 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Hurlstone 2005 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Hurlstone 2006</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Hurlstone 2007 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Hurlstone 2008 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Hurlstone 2010 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>James Ruse</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2001 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2002 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2003 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2004 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2005 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2006 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2007 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2008 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2009 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2010 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2011 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2012</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2013</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2015</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2016 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2018 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2019 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2021 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>James Ruse 2022 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Knox</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Knox 2022</a>
</span></details></td></tr>
<tr><td><details open><summary>North Sydney Boys</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>North Sydney Boys 2021</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>North Sydney Boys 2022</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>North Sydney Boys 2024</a>
</span></details></td></tr>
<tr><td><details open><summary>North Sydney Girls</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>North Sydney Girls 2018</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>North Sydney Girls 2020</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>North Sydney Girls 2021</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>North Sydney Girls 2022</a>
</span></details></td></tr>
<tr><td><details open><summary>Scots</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1821)}>Scots 2018 w. sol</a>
</span></details></td></tr>

<tr><td><h5 id="task-2-exams">CT2 Feb-Mar Assessments</h5></td></tr>
<tr><td>No exams. See also the HY exams posted above.</td></tr>
<tr><td><h5 id="task-3-exams">CT3 May-Jun Assessments</h5></td></tr>
<tr className="content"><td>Typically Task 3 exams held in Term 2</td></tr>
<tr><td>&nbsp;</td></tr>

<tr><td><details open><summary>Hurlstone</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>Hurlstone 2004</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>Hurlstone 2005 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>Hurlstone 2006</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>Hurlstone 2008 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>Hurlstone 2009 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>Hurlstone 2011 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>James Ruse</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2002 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2003 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2004 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2005 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2006 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2007 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2008 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2009 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2010 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2011 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2012 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2013 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 1823)}>James Ruse 2014 w. sol</a>
</span></details></td></tr>

</tbody></table>
</div>
        </>
    );
}
