// AUTO-GENERATED BY sync.ps1
// Source: yr12\LOTE\index.html

export const title = "THSC Online - HSC Languages Resources";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;    
<a className="current" href="/s/yr12/LOTE/">Languages →</a>&nbsp;    
<a className="reverse" href="../">↖ [<i>Up One Folder</i>]</a>    
</div></div>
<div id="content-all">
<h3><span className="title"><img src="/s/images/colours/icon_pink.png">&nbsp;&nbsp;HSC Languages Resources</span></h3>
<div id="web-list">
<div><div><div>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png">&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br>
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="../">Back to Year 12 - HSC</a></span><br><br>
</details>
<span><img src="/s/images/colours/icon_lavender.png">&nbsp;&nbsp;
<a href="Japanese/">Japanese <small>(Beginners, Continuers, Extension)</small></a></span><br>
<span><img src="/s/images/colours/icon_cloudy.png">&nbsp;&nbsp;
<a href="Latin/">Latin <small>(Continuers, Extension)</small></a></span><br>

<br>
<span><b>General Resources for All Languages</b></span><br>
<span><img src="/s/images/icon_pdf2.png">&nbsp;&nbsp;
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4200)}>Character Grid for Asian Languages (A5 Size)</a></span><br>
<span><img src="/s/images/icon_pdf2.png">&nbsp;&nbsp;
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4200)}>Practice Questions - Short Writing Tasks</a></span><br>
<span><img src="/s/images/icon_pdf2.png">&nbsp;&nbsp;
<a href="#v" onClick={(e) => pdf(e.currentTarget, 4200)}>Practice Questions - Extended Writing Tasks</a></span><br>
</div></div></div></div>
</div>
        </>
    );
}
