// AUTO-GENERATED BY sync.ps1
// Source: yr11\Economics\prelimpapers.html

export const title = "THSC Online - Year 11 Economics Yearly Exam Papers";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="current"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="element"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr11/">Year 11 - Preliminary →</a>&nbsp;
<a href="/s/yr11/Economics/">Economics →</a>&nbsp;
<a className="current" href="/s/yr11/Economics/prelimpapers.html">Past Yearly Exams →</a>&nbsp;
<a className="reverse" href="index.html">↖ [<i>Up One Folder</i>]</a>
</div></div>  
<div id="content-all">
<h4>Year 11 Economics Yearly Exams</h4>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png">&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br>
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="../">Back to Year 11 - Preliminary</a></span><br>
<span><img src="/s/images/icon_back.png">&nbsp;&nbsp;
<a href="index.html">Up One Folder</a></span><br><br>
</details>
<table className="listing" id="papers-by-school"><tbody>
<tr className="content"><td><span style="color:#0000FF;"><b>Note: </b></span>Some materials listed are from old syllabus prescriptions.</td></tr>
<tr className="content"><td><span style="color:#0000FF;"><b>Note 2: </b></span>2021 exams were conducted online, so the format of materials listed may differ slightly.</td></tr>
<tr className="content"><td>
<ul>
<li>Sample answers or marking guidelines included with most papers.</li>
<li>To contribute past papers or other practice questions, <a href="/s/upload">upload files here</a></li>
</ul></td></tr>
<tr><td>Fort St<br>
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Fort St 2010 w. sol</a>
</span></td></tr>
<tr><td>Newington<br>
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Newington 2012 w. sol</a><br>
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Newington 2013 w. sol</a><br>
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Newington 2014 w. sol</a><br>
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Newington 2015 w. sol</a>
</span></td></tr>
<tr><td>Penrith<br>
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Penrith 2016</a>
</span></td></tr>
<tr><td>Pymble<br>
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Pymble 2004</a>
</span></td></tr>
<tr><td>Riverview<br>
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Riverview 2019 w. sol</a>
</span></td></tr>
<tr><td>Sydney Grammar<br>
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Sydney Grammar 2014 w. sol</a><br>
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Sydney Grammar 2015 w. sol</a>
</span></td></tr>
<tr><td>Sydney Tech<br>
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Sydney Tech 2011</a><br>
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Sydney Tech 2012 w. sol</a><br>
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2468)}>Sydney Tech 2013 w. sol</a>
</span></td></tr>
</tbody></table>
</div>
        </>
    );
}
