// AUTO-GENERATED BY sync.ps1
// Source: yr12\Economics\trialpapers.html

export const title = "THSC Online - HSC Economics Trial Papers";

export default function Page() {
    return (
        <>
<div id="navigation">
<ul>
<li className="element"><a href="/s/">THSC Home</a></li>
<li className="element reducible"><a href="/s/yr9/">Year 9</a></li>
<li className="element"><a href="/s/yr10/">Year 10</a></li>
<li className="element"><a href="/s/yr11/">Year 11 - Preliminary</a></li>
<li className="current"><a href="/s/yr12/">Year 12 - HSC</a></li>
<li className="element reducible"><a href="/s/upload/">Upload Files</a></li>
</ul>
<div id="folder-tree">
<a href="/s/">thsconline →</a>&nbsp;
<a href="/s/yr12/">Year 12 - HSC →</a>&nbsp;
<a href="/s/yr12/Economics/">Economics →</a>&nbsp;
<a className="current" href="/s/yr12/Economics/trialpapers.html">Past Trials →</a>&nbsp;
<a className="reverse" href="#v" onClick="toggleSearchBar()">&nbsp;&nbsp;🔎︎ [<i>Search</i>]</a>
<a className="reverse" href="index.html">↖ [<i>Up One Folder</i>]</a>
</div></div>  
<div id="content-all">
<h4>HSC Economics Trial Papers</h4>
<details className="smallscreen" style="display:none;"><summary>&nbsp;</summary>
<span><img src="/s/images/icon_home.png" />&nbsp;&nbsp;
<a href="/s/">Home Page</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="../">Back to Year 12 - HSC</a></span><br />
<span><img src="/s/images/icon_back.png" />&nbsp;&nbsp;
<a href="index.html">Up One Folder</a></span><br /><br />
</details>
<table className="listing" id="papers-by-school"><tbody>
<tr className="search" id="search-row" style="display: none;"><td>
<input type="text" id="search-bar" onKeyUp={filterTable} placeholder="Search this page..." />
<label><input type="checkbox" id="search-exact" onClick={filterTable} /> Show exact matches only</label>&nbsp;&nbsp;
<label><input type="checkbox" id="search-wsol-only" onClick={filterTable} /> Show only papers that have solutions</label>
<br />
<span id="search-message"></span>
</td></tr>
<tr className="content"><td><span style="color:#0000FF;"><b>Note: </b></span>Some materials listed are from old syllabus prescriptions.</td></tr>
<tr className="content"><td><span style="color:#0000FF;"><b>Note 2: </b></span>2021 exams were conducted online, so the format of materials listed may differ slightly.</td></tr>
<tr className="content"><td>
<ul>
<li>Sample answers or marking guidelines included with most papers.</li>
<li>To contribute past papers or other practice questions, <a href="/s/upload">upload files here</a></li>
</ul></td></tr>

<tr><td><details open><summary>Abbotsleigh</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Abbotsleigh 2012 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Abbotsleigh 2013 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Abbotsleigh 2016</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Abbotsleigh 2017 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Abbotsleigh 2021 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Abbotsleigh 2023 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Ascham</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Ascham 2018 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Barker</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Barker 2001</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Barker 2009 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Barker 2010 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Barker 2011 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Barker 2012 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Barker 2013 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Barker 2020</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Barker 2022 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Baulkham Hills</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Baulkham Hills 2019</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Baulkham Hills 2022 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Baulkham Hills 2023 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Baulkham Hills 2024 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Baulkham Hills 2025 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Cranbrook</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Cranbrook 2001</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Cranbrook 2021</a>
</span></details></td></tr>
<tr><td><details open><summary>Fort St</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Fort St 2010</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Fort St 2011</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Fort St 2012</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Fort St 2021 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>James Ruse</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>James Ruse 2017 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>James Ruse 2021 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Kings</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Kings 2022 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Knox</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Knox 2012 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Knox 2013 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Knox 2020 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Knox 2021 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Knox 2022</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Knox 2023</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Knox 2024 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Knox 2025 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Manly</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Manly 2018 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Newington</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Newington 2003</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Newington 2004 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Newington 2005 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Newington 2006 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Newington 2007 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Newington 2013 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Newington 2016 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Newington 2017 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Newington 2025 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Normanhurst Boys</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Normanhurst Boys 2021</a>
</span></details></td></tr>
<tr><td><details open><summary>North Sydney Girls</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>North Sydney Girls 2009</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>North Sydney Girls 2010</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>North Sydney Girls 2011</a>
</span></details></td></tr>
<tr><td><details open><summary>Pymble</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Pymble 2001</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Pymble 2006 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Pymble 2021</a>
</span></details></td></tr>
<tr><td><details open><summary>Ravenswood</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Ravenswood 2012 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Ravenswood 2014</a>
</span></details></td></tr>
<tr><td><details open><summary>Riverview</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Riverview 2005</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Riverview 2006</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Riverview 2007</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Riverview 2009 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Riverview 2010 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Riverview 2011 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Riverview 2012 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Riverview 2013 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Riverview 2015 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Riverview 2017</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Riverview 2021 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Riverview 2024 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>SCEGGS</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>SCEGGS 2016 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Scots</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Scots 2012</a>
</span></details></td></tr>
<tr><td><details open><summary>Shore</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Shore 2001</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Shore 2012 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Shore 2013 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Shore 2018 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Sydney Boys</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Boys 2020 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Boys 2021</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Boys 2022 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Boys 2025 w. sol</a>
</span></details></td></tr>
<tr><td><details open><summary>Sydney Grammar</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Grammar 2008</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Grammar 2016</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Grammar 2017 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Grammar 2019 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Grammar 2020 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Grammar 2021 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Grammar 2025</a>
</span></details></td></tr>
<tr><td><details open><summary>Sydney Tech</summary><br />
<span className="content">
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Tech 2011 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Tech 2013 w. sol</a><br />
<a href="#v" onClick={(e) => pdf(e.currentTarget, 2478)}>Sydney Tech 2014 w. sol</a>
</span></details></td></tr>

</tbody></table>
</div>
        </>
    );
}
